### ISSUE TITLE
As a team, we have sufficient testing & related processes to launch

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#2146]
## Background
Before we launch to the public, we need a clear testing plan and sufficient testing to ensure a positive user experience. 

### Regression testing
_Metrics: #bugs by priority (low, med, high) // test coverage % (#tests / scenarios needed)_
- [ ] Restart E2E testing
- [ ] Create a testing plan + checklist of all features/scenarios we check to work in releases
- [ ] [TBD] Create local testing environments and automated testing with Harbor team
- [ ] [TBD] Unit testing is on all critical features 

Out of scope:
- Automated regression testing with full test coverage 

### Load testing 
_Metrics: 
TTV, TTR, TPS (txns/second), Success rate, [Uptime (link)](https://connext.betteruptime.com/)_
- [ ] Create metrics/monitoring of TPS and success rate for user load
- [ ] Ensure TTV and TTR are accurate and available
- [X] Ensure uptime is available for Router + Sequencer
- [ ] Ensure uptime is measured for Cartographer and Lighthouse

Out of scope
- Manual / automated load testing (due to time we are instead using community beta testers to simulate load and focusing on monitoring/metrics)
- Stress testing (testing very extreme loads) 

### Process Needs
- [ ] Restart beta testing with the community to simulate load testing
- [ ] Finalize bug intake - channels and processes around prioritization, assignment, and comms [LINK to process](https://www.notion.so/connext/On-Call-Process-8094f702b3e247f6a40315581fb7984d#2a160a5af212420abb8a706a5905ea08)
- [ ] Clear owner/cadence of monitoring metrics (ie oncall)
- [ ] Run company testing and bug finding efforts outside eng team

## Sub Tasks
- [ ] Restart E2E testing
https://github.com/connext/nxtp/issues/2203
- [X] Uptime on Lighthouse and Cartographer https://github.com/connext/nxtp/issues/1725
- [ ] Testing plan + scenario checklist
https://github.com/connext/nxtp/issues/2202
- [ ] Measure load + reliability (TPS, success)
https://github.com/connext/nxtp/issues/2201

## Notes and links
https://www.notion.so/connext/Amarok-Launch-Testing-Notes-ed202391fbc644279245c82d59e94c5e
https://twitter.com/goharborhq
