### ISSUE TITLE
As a user, all new UIs are usable with strong UX

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#2165]
## Background
Our Bridge, Pool,  Swap, and Explorer UIs need MVP functionality and are polished before launching

## Definition Of Done
- [ ] nxtp-v1 has a banner and call to action to try Amarok
Bridge
- [ ] Bridge transfers work slow and fast path + all settings work
- [ ] Necessary settings are hidden pre-launch
- [ ] Recent transfers works as expected and links to explorer cleanly
- [ ] User is notified of slippage failing and has action to bump / wait 
Pool
- [ ] User can add and remove liquidity
- [ ] User can view pool critical metrics in the UI 
- [ ] Token pairs are correct 
Swap
- [ ] User can swap assets on any chain 
- [ ] User can view swap metrics ie slippage
Explorer
TBD
