### ISSUE TITLE
Scale Connext Relayer

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#2461]
## Background

Connext relayer should scale horizontally.

## Definition Of Done

Connext relayer can handle 100 tx/min with  avg TTV <= 3mins

## Tasks

- [ ] Split relayer into pub - sub
- [ ] Setup MQ on AWS
- [ ] Create >= 10 relayer EOAs and fund it on goerli, mumbai, and polygon
- [ ] Create new docker images
- [ ] Add TF config
- [ ] Load test and scale till 100 tx/min with  avg TTV <= 3mins
