### ISSUE TITLE
As a user, I want to be able to use zkSync testnet in order to develop xapps on it.

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#2851]
## Problem
Let's launch zkSync.

## Proposed Solution
Connector already exists.
- [ ] Deploy contracts on zkSync testnet.
- [ ] Hook up connectors
- [ ] Test

## Acceptance Criteria
- [ ] zkSync support is available to Connext integratoooors.
