### ISSUE TITLE
Watcher Mistaken Firing

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#3144]
## Background

- Watcher fired `pause` with the following error:

```
Connext Watcher Alert - totalMintedAssets (619480292707) is less than or equal to totalLockedAssets (32) for 0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48
```

despite >700K in USDC on mainnet chains.

### Tasks

- [x] to have consistent request context for the entirety of an interval
- [x] to have the same debug logs around direct data used and retrieved for totalMintedAssets
- [x] to have the same debug logs around direct data used and retrieved for totalLockedAssets
- [x] enforce minimum providers on watcher
- [x] log and pull the latest transaction hashes from the previous unalerting interval
- [x] allow txservice config to specify a fallback provider quorum, increase this to >1 in the watcher

### Linked Issues & Documentation

- BetterUptime incident: https://betteruptime.com/team/40435/incidents/330137557

**Comment by LayneHaber** [comment]
from @jakekidd 

Two immediate lessons before i forget:
1. Need to know which transfer(s) did the dirty, watcher alert should display suspect transaction hashes
2. Need to know which connext on which chain where this happened ^ but i guess that goes hand in hand with tx hash

1 should be a task -- log and pull the latest transaction hashes from the previous unalerting interval

**Comment by LayneHaber** [comment]
also needs to have consistent request context for the entirety of an interval

**Comment by LayneHaber** [comment]
update on rca:
- none of the logs for the interval where things were paused include results from the asset amounts, only which assets we were querying (all correct). this makes it difficult to narrow down why the alert fired, though most likely its because this code returned an incorrect value:

```ts
const getCustodiedAmountCalldata = ConnextInterface.encodeFunctionData("getCustodiedAmount", [assetKey]);
    const amountRes = await this.context.txservice.readTx({
      domain: +asset.canonicalDomain,
      to: connext.address,
      data: getCustodiedAmountCalldata,
    });
    try {
      return ConnextInterface.decodeFunctionResult("getCustodiedAmount", amountRes)[0];
```

- there are 5 mainnet providers, all of which work
- within the txservice, there are a couple of things:
1. there is a `fallbackProvider`, but it uses a quorum of 1, [src](https://github.com/connext/monorepo/blob/a1e10be0ede3cf4476e7d158998d3f036bf55806/packages/adapters/txservice/src/aggregator.ts#L118) 
2. the `fallbackProvider` is not what handles the contract reads, instead it is the `SyncProvider` class which extends `StaticJsonProvider` and intercepts the `send` method (but not the call method), see [here](https://github.com/connext/monorepo/blob/a1e10be0ede3cf4476e7d158998d3f036bf55806/packages/adapters/txservice/src/shared/provider.ts#L11-L15) and [here](https://github.com/connext/monorepo/blob/a1e10be0ede3cf4476e7d158998d3f036bf55806/packages/adapters/txservice/src/aggregator.ts#L290-L294)
3. the `BaseProvider` class used in ethers actually doesnt use the send method when call is invoked, so we actually dont get `SyncProvider` benefits when using read transactions, [src](https://github.com/ethers-io/ethers.js/blob/bf0b468490cb293cd916e4fff06e0909273719e6/packages/providers/src.ts/base-provider.ts#L1631-L1730)

that means the most likely scenario causing the error was one of the mainnet providers returning a bad custodied value despite being synced. the steps to remedy this are:
- allow `txservice` config to specify a fallback provider quorum, increase this to >1 in the watcher
- query the total linked / minted values using the fallback provider instead of the standard `readTx`
