### ISSUE TITLE
Amarok launch tasks

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#3328]
## Background

There will be a larger announcement for Amarok launch made at 10am ET. We want to have the following changes made *before* this announcement.

## Tasks

- [x] Move Bridge UI from amarok.bridge.connext.network to bridge.connext.network (pools as well)
- [x] Set up permanent redirect (301) for amarok.bridge.connext.network 
- [x] Move V1 to v1.bridge.connext.network
- [x] Link v1 in UI

- [x] Move Amarok Explorer from amarok.connextscan.io to connextscan.io
- [x] Set up permanent redirect (301) for amarok.connextscan.io 
- [x] Move V1 to v1.connextscan.io
- [x] Link V1 at top of explorer

**Comment by alexwhte** [comment]
accidently filed a dupe #3339, let's use this one

**Comment by pjenviri** [comment]
@alexwhte can we turn off the v1 testnet explorer?

**Comment by alexwhte** [comment]
@rhlsthrm ?

**Comment by rhlsthrm** [comment]
Yes we can turn of v1 testnet explorer and all v1 testnet UIs.

**Comment by pjenviri** [comment]
Got it. Turned it off. Re-closing the issue.
