### ISSUE TITLE
As a contract deployer, I want to run an upgrade test suite in order to derisk deployments.

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#3418]
## Problem

We need a safe way to test upgrades of the execution layer contracts before proposing them to reduce possibility of foot guns.

## Proposed Solution

Create a robust upgrade testing suite. Should:

#3419
#3420
#3421
#3422
#3423
#3424
#3425
#3426

## Acceptance Criteria

- [ ] Tests run against all mainnet forks
- [ ] Bridging tests run against all combinations of mainnet forks
- [ ] Upgrades cannot be proposed without record of corresponding passing tests
