### ISSUE TITLE
processes for subgraph updates on Prod

### ISSUE THREAD

**Issue by sanchaymittal** [connext/monorepo#3529]
## Problem
_What problem are we solving and why does it matter, ser?_ 

- Subgraph is the data source for all the agents, we need to treat it as a critical update.
- When we update subgraph link, we use the links at the graph client to push the updates. In case schema changes happen the steps in between where the subgraph is updated and the regenerated graph client are pushed to prod. we will see downtime.

## Proposed Solution
_Thoughts on solution design. We should do <insert idea> to solve this problem._

- [ ] create staging subgraph for prod mainnet
- [ ] update graph client using env(use staging subgraph to generate client locally).
- [ ] write document for subgraph update on prod process.

## Acceptance Criteria
_From an end tester and/or user perspective, the below criteria must be met to consider this done:_
- [ ] X happens
