### ISSUE TITLE
Multi-router liquidity logic

### ISSUE THREAD

**Issue by sanchaymittal** [connext/monorepo#3530]
## Problem
As of now, we are dividing the liquidity in the same ratio of multi routers. 
Basically we had a 21 ETH transfer. One router had 8.7 ETH and one had 19.9ETH. Because they would need to equally split, it couldnt go fast path, even through there was enough ETH between them. 

## Proposed Solution
Add extra signatures for remainder router calculation 
Sequencer adds that together 
Same logic for all assets

To utilize the full scope of liquidity multi-router, we could have a way for routers to cover remainders after even splits. 

## Acceptance Criteria
_From an end tester and/or user perspective, the below criteria must be met to consider this done:_
- [ ] If a transfer is sent and there is enough router liquidity in a single router or across a few routers, then the transfer should always succeed 
- [ ] Even splits should still be the initial priority, where possible 
- [ ] This is in a testable prototype

**Comment by preethamr** [comment]
Needs contract changes. Should be tasked accordingly.

**Comment by alexwhte** [comment]
Reopening and updated for discussion. Im not sure how serious of a change this is + with the token freeze

**Comment by liu-zhipeng** [comment]
We need to upgrade connext diamond contract to do this.

**Comment by sanchaymittal** [comment]
@wanglonghong started looking into this one. Will be asking some question around it

**Comment by rhlsthrm** [comment]
Finishing up spec, need review.

**Comment by rhlsthrm** [comment]
Spec is complete, going ahead with implementation.

**Comment by sanchaymittal** [comment]
Spec: https://www.notion.so/connext/Multi-Router-Liquidity-4dd927a0a96e4f84b2b20142db4e5493?pvs=4

We need an Integration test for the scenario, after slow path in implemented. We can start with it's implementation and testing.

**Comment by LayneHaber** [comment]
stale, closing
