### ISSUE TITLE
New SDK + API

### ISSUE THREAD

**Issue by ArjunBhuptani** [connext/monorepo#3732]
SDK currently imports too many dependencies, resulting in a bloated bundle which can be untenable for integrators. 

New SDK spec: https://www.notion.so/connext/Connext-New-SDK-Spec-fa52e9f465314102b47cf82f233013c3

**Comment by alexwhte** [comment]
now that we're relying a lot on SDK for integrations were starting to see some issues with it being bloated and pulling in a lot of deps which it doesnt need. i think its worth redesigning the SDK and deps from the ground up to make sure its super lightweight and works super well
some dapps wont integrate us if the SDK is over a certain bundle size

https://discord.com/channels/992549151134982234/1083352842133319720

**Comment by rhlsthrm** [comment]
https://www.notion.so/connext/SDK-Optimization-3749cc1cd7824e568df5ca153fe351c8?pvs=4

Scoped here.

**Comment by alexwhte** [comment]
@just-a-node will add Chai stuff to the spec

**Comment by rodsouto** [comment]
Hi, I'm having this problem too. I just need to estimate the relayer fee, but installing the sdk increases the bundle size almost 2.5MB (a 3.4x increase compared to the previous size). 

It would be great to have better tree shaking support to improve this.

**Comment by rhlsthrm** [comment]
Adding spec here:

Tasks:
- [ ] Remove `fs` and `path` dependencies. Likely requires creating a secondary package with only SDK-needed utils.
- [ ] Remove `contracts` dependency. Create a minimal contracts export which contains minimal contract addresses and ABIs. Might need to be manually generated for now.
- [ ] [Tree shaking](https://webpack.js.org/guides/tree-shaking/). Requires bundling with Webpack.
- [ ] Migrate from Ethers (large bundle size) to [Viem](https://viem.sh/) which is fully optimized.

**Comment by alexwhte** [comment]
**Complexity: 13**
  [See the discussion](https://action.parabol.co/meet/lUA9WjpFoA/estimate/4) in Backlog Prio 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Impact: 4**
  [See the discussion](https://action.parabol.co/meet/lUA9WjpFoA/estimate/5) in Backlog Prio 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Urgency: 3**
  [See the discussion](https://action.parabol.co/meet/lUA9WjpFoA/estimate/6) in Backlog Prio 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Complexity: 13**
  [See the discussion](https://action.parabol.co/meet/m6kwOazA4M/estimate/13) in Sprint Poker #​​26

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Impact: 4**
  [See the discussion](https://action.parabol.co/meet/m6pgrIxPdS/estimate/23) in Sprint Poker #​​27

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Urgency: 4**
  [See the discussion](https://action.parabol.co/meet/m6pgrIxPdS/estimate/24) in Sprint Poker #​​27

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Complexity: 21**
  [See the discussion](https://action.parabol.co/meet/mhZ41q7j3O/estimate/17) in Sprint Poker #​​29

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Impact: 4**
  [See the discussion](https://action.parabol.co/meet/mi1RgQ7yzS/estimate/33) in Sprint Poker #​​30

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Urgency: 3**
  [See the discussion](https://action.parabol.co/meet/mi1RgQ7yzS/estimate/34) in Sprint Poker #​​30

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
note: Max from LiFi complained about server issues last week. Doing this will enable us to move out of server to stop hosting SDK

**Comment by alexwhte** [comment]
note off of recent Socket issues:  
Aggregator integrations can technically read pool contracts to see if there's enough liquidity. 
SDK could have helper functions to make that easier. But relying on that can run into issues with too many calls

**Comment by t0rbik** [comment]
Hey all, is there an ETA for the update? Thanks.

**Comment by just-a-node** [comment]
We'll be releasing an Everclear API so this will be sunset
