### ISSUE TITLE
Calculate gas costs for adding zkSync to mainnet

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#3797]
## Background

We need an accurate estimate for how much adding zkSync to mainnet will cost.

## Definition Of Done

We have an accurate estimate of monthly gas costs on ETH mainnet.

## Tasks

- [ ] Check how much `propagate` cost will increase.
- [ ] Check how much each `processFromRoot` will cost.
- [ ] Assuming each of these is done on 30 minute intervals, calculate the total spend per month,
