### ISSUE TITLE
Optimize Lambda costs

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#3818]
## Background

Lambdas with the current memory config are quite expensive to run. We should optimize this by configuring lambdas individually based on their usage.

### Linked Issues & Documentation

https://app.cloudcraft.co/blueprint/da85fcd9-3fe4-4792-8667-98b1ce102ec2 for usage.

## Definition Of Done

Lambdas are individually configured for mem usage.

## Tasks

- [ ] Check mem usage of Lambdas.
- [ ] Choose appropriate configuration per Lambda.
- [ ] Configure TF to individually specify mem options.
