### ISSUE TITLE
Midas add swap functionality

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3839]
## Background

We have integrated a basic version of Connext into Midas. We will take this integration to the next level by integrating the swapper contract to do a destination swap into the desired position.

### Linked Issues & Documentation

- List of linked issues, external links, etc

## Definition Of Done

Midas UI supports swapping into desired token to create position.

## Tasks

- [x] Integrate swapper contract into xReceive.
- [x] Integrate fallback address instead of owner-controlled sweeper.
- [x] SDK method to generate SwapData #3971 
- [ ] Integrate into Midas front end. Show things like estimated slippage.
- [ ] Test to make sure swaps occur.

**Comment by alexwhte** [comment]
**Impact: 3**
  [See the discussion](https://action.parabol.co/meet/lUA9WjpFoA/estimate/44) in Backlog Prio 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Urgency: 3**
  [See the discussion](https://action.parabol.co/meet/lUA9WjpFoA/estimate/45) in Backlog Prio 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Complexity: 21**
  [See the discussion](https://action.parabol.co/meet/m1gPDfcYUg/estimate/10) in Sprint Poker #​​22

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by rhlsthrm** [comment]
Completed writing target contract and created unit/integration tests. Resolving comments. Need to do SDK next.

**Comment by rhlsthrm** [comment]
Pushed fixes for PR, waiting for review. Kick off SDK stuff after this.

**Comment by rhlsthrm** [comment]
Contracts side is done. Creating packages for chain abstraction integrators.

**Comment by rhlsthrm** [comment]
Closing since the rest of the tasks are in other issues.
