### ISSUE TITLE
Fix release versioning

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#3884]
## Background

Our current release process is broken due to all packages being versioned together. We need to version the following items independently for release:
- SDK (NPM)
- Contracts (NPM)
- Utils (NPM)
- TxService (NPM)
- Router (Docker)
- Watcher (Docker)

We also need to update our CI jobs such that they release these packages individually based on the need to be released only.

### Linked Issues & Documentation

- List of linked issues, external links, etc

## Definition Of Done

Release process happens independently based on package versions and git tags.

## Tasks

- [ ] Revert root package.json to version 0.0.0 to avoid confusion.
- [ ] Remove `version:all` script.
- [ ] Use [Yarn version tooling](https://yarnpkg.com/features/release-workflow) to version packages based on release need.
- [ ] Modify CI task for SDK release. If tag is `sdk:vX.Y.Z`, publish SDK and all dependent packages to NPM.
- [ ] Modify CI task for router release. If tag is `router:vX.Y.Z`, publish router docker image with proper version tag.
- [ ] Modify CI task for watcher release. If tag is `watcher:vX.Y.Z`, publish watcher docker image with proper version tag.
- [ ] Internally document the process for creating releases.

Note: For now, do not create CI jobs for dependency packages such as utils, txservice since these are not consumed outside the SDK. Subject to change.
