### ISSUE TITLE
[documentation] New connectors documented

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#4002]
## Background

Any information that gives more context as to why this task exists, and why it matters. This might include: links to discussions, documentation, or other Jira issues / tasks

### Linked Issues & Documentation

- [Notion task list](https://www.notion.so/connext/Messaging-Layer-Upgrade-Checklist-56ec9377171f4266910d74a868ba3221)
- [Notion spec](https://www.notion.so/connext/Messaging-Layer-Audit-Scope-826b9ac2d43d47bf9f46bb4145aa6527)

## Definition Of Done

Documentation is completed and referenced sin the scope document.

## Tasks

Should be completed for each chain:
- Consensys ZkEVM
- ZkSync
- Polygon ZkEVM

- [x] Link resources in scope (including vendor documentation links)
- [ ] Completed video walkthrough
- [x] Ensure connector logic documented in core protocol documentation (and linked in scope doc)

**Comment by rhlsthrm** [comment]
Docs in progress.

**Comment by rhlsthrm** [comment]
Video walkthrough today.

**Comment by rhlsthrm** [comment]
Filmed one of videos, try to do rest today.

**Comment by rhlsthrm** [comment]
Finished videos.
