### ISSUE TITLE
[documentation] Adapters / XReceivers

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#4003]
## Background

Need to prepare documentation of the following contracts for the audit:
- [ ]  Adapters
    - [ ]  `SwapAdapter`
- [ ]  Swappers
    - [ ]  `OneInchUniswapV3`
    - [ ]  `UniV2Swapper`
    - [ ]  `UniV3Swapper`
- [ ]  Origin Helpers
    - [ ]  `SwapAndXCall` (is `SwapAdapter`)
- [ ]  Receivers
    - [ ]  `ForwarderXReceiver`
        - [ ]  `UniswapV2ForwarderXReceiver`
        - [ ]  `UniswapV3ForwarderXReceiver`
        - [ ]  `SwapForwarderXReceiver` (is `SwapAdapter`)
    - [ ]  `AuthForwarderXReceiver`

### Linked Issues & Documentation

- [Notion task list](https://www.notion.so/connext/Messaging-Layer-Upgrade-Checklist-56ec9377171f4266910d74a868ba3221)
- [Notion spec](https://www.notion.so/connext/Messaging-Layer-Audit-Scope-826b9ac2d43d47bf9f46bb4145aa6527)

## Definition Of Done

Documentation is completed and referenced in the scope document.

## Tasks

- [ ] Link resources in scope (including vendor documentation links)
- [ ] Completed video walkthrough
- [ ] Ensure each swapper / adapter flow is documented in a branch in the user-facing documentation, and referenced in the scope document.

**Comment by just-a-node** [comment]
https://github.com/connext/documentation/pull/101

**Comment by rhlsthrm** [comment]
@sanchaymittal continue docs in PR.

**Comment by rhlsthrm** [comment]
@rhlsthrm start video walkthrough today.
@sanchaymittal going to look at user docs.

**Comment by rhlsthrm** [comment]
Video walkthrough + wrap up of auditor docs.

**Comment by rhlsthrm** [comment]
@sanchaymittal adding more to user facing docs. Will look at auditor docs.

**Comment by rhlsthrm** [comment]
@rhlsthrm fleshing out remaining audit docs and video walkthroughs.

**Comment by rhlsthrm** [comment]
Done with video walkthrough and full docs.
