### ISSUE TITLE
[documentation] Conductor

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#4004]
## Background

Need to prepare documentation on the `Conductor` contract and it's usage in future upgrades.

### Linked Issues & Documentation

- [Notion task list](https://www.notion.so/connext/Messaging-Layer-Upgrade-Checklist-56ec9377171f4266910d74a868ba3221)
- [Notion spec](https://www.notion.so/connext/Messaging-Layer-Audit-Scope-826b9ac2d43d47bf9f46bb4145aa6527)

## Definition Of Done

Documentation is completed and referenced in the scope document.

## Tasks

- [x] Link resources in scope (including vendor documentation links)
- [x] Completed video walkthrough
- [x] Ensure `Conductor` has internal spec, which includes information about how it will be used in the upgrades and its intended functionality.
