### ISSUE TITLE
[documentation] Optimistic roots message flow

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#4005]
## Background

Need to prepare documentation of the optimistic roots feature and message flow.

### Linked Issues & Documentation

- [Notion task list](https://www.notion.so/connext/Messaging-Layer-Upgrade-Checklist-56ec9377171f4266910d74a868ba3221)
- [Notion spec](https://www.notion.so/connext/Messaging-Layer-Audit-Scope-826b9ac2d43d47bf9f46bb4145aa6527)

## Definition Of Done

Documentation is completed and referenced in the scope document.

## Tasks

- [x] Link resources in scope (including vendor documentation links)
- [x] Completed video walkthrough
- [x] Ensure the contracts have a walkthrough (specifically, updated message flow in fast and slow path)
- [ ] (maybe?) Ensure there are updates to the core protocol flow reflected in a docs branch
