### ISSUE TITLE
Add asset support for Linea zkEVM testnet

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#4029]
## Background

Linea wants to run testnet quests. We need to support MATIC and USDC Polygon Mumbai <> Linea.

We will be using nextMATIC as canonical so we do not need an LP. We need an LP on Mumbai for USDC/nextUSDC.

### Linked Issues & Documentation

- List of linked issues, external links, etc

## Definition Of Done

USDC and MATIC are bridgeable. MATIC canonical domain is Mumbai. USDC canonical domain is Goerli.

## Tasks

- [ ] Set up USDC asset on Linea with adopted = Linea USDC.
- [ ] Set up USDC asset on Matic with adopted = PoSUSDC.
- [ ] Set up MATIC on Linea with adopted = local.
- [ ] Set up MATIC on Mumbai as canonical.

**Comment by rhlsthrm** [comment]
Assets set up. Continuing testing today.

**Comment by rhlsthrm** [comment]
Testing and figuring out final issues.
