### ISSUE TITLE
[ops] Make Harbor work with our stack

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#4040]
## Background

Need Harbor for sophisticated local testing scenarios, particularly for the optimistic root upgrade.

Much of this work has been started in #2665

### Linked Issues & Documentation

- [Full specification](https://www.notion.so/connext/DRAFT-Harbor-Integration-Testing-a6bbd143dc654c11afeda2449bffbe9a?p=a7ec19cb3b3943168a880a3947659eea&pm=s)

## Definition Of Done

Our contracts and agents are able to be properly deployed on harbor.

## Tasks

- [ ]  Execution layer is deployed to harbor
- [ ]  Messaging layer is deployed to harbor (with properly-mocked AMBs)
- [ ]  Contracts must be properly init-d
- [ ]  Agents are properly deployed
- [ ]  Local system can be brought up, is documented, and liveness of agents tested (i.e. `/ping` endpoints work successfully)

**Comment by LayneHaber** [comment]
Closing this, as currently we are running into some issues that have been taking a while to resolve. This was originally supposed to be the bedrock of the upgrade suite testing, but for now we will likely use tenderly endpoints (or something equivalent)
