### ISSUE TITLE
[ops] Harbor in CI/CD

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#4041]
## Background

Need local testing framework available and run in CI to avoid regressions of major functionality.

### Linked Issues & Documentation

- [Specification](https://www.notion.so/connext/DRAFT-Harbor-Integration-Testing-a6bbd143dc654c11afeda2449bffbe9a?p=196545252fe24019a8c09f3f9563f53f&pm=s)

## Definition Of Done

Local tests (see below scenarios) run in CI with the full stack.

## Tasks

- [ ]  Should test fast path
    - [ ]  WETH / ETH
    - [ ]  tokens
- [ ]  Should test slow-path
    - [ ]  WETH / ETH
    - [ ]  tokens
- [ ]  Relayer fees (optional)
    - [ ]  Works with transacting asset
    - [ ]  Works with native asset
    - [ ]  Works with multiple bumps
    - [ ]  Works with multiple assets
- [ ]  Slippage
    - [ ]  It should be addressable / detectable via the sdk
    - [ ]  It should handle multiple bumps

**Comment by alexwhte** [comment]
@LayneHaber please close and replace

**Comment by LayneHaber** [comment]
Replaced with #4042
