### ISSUE TITLE
Get everything in testnet to process

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#4225]
## Background

There are still hundreds of thousands of unprocessed messages in the DB. In order to have a fully working testnet, all these have to be back to 0 pending and everything processed.

### Linked Issues & Documentation

- List of linked issues, external links, etc

## Definition Of Done

All messages and root_messages are processed in DB (except any brand new messages that need to be processed).

## Tasks

- [ ] Process old `root_messages`
- [ ] Process old `messages`
- [ ] Ensure any new entries process in a timely manner

**Comment by rhlsthrm** [comment]
Still running slowly to get through.

**Comment by rhlsthrm** [comment]
Gelato 1balance out of funds on testnet, need to refill this.

**Comment by alexwhte** [comment]
Pending:
1. Merge Preetham's PR on concurrency for lighthouse prover
2. Work on fixing the round robin mechanism

**Comment by rhlsthrm** [comment]
RPC issues with Linea RPC, need to get node running properly.

**Comment by rhlsthrm** [comment]
@wanglonghong local stuff is crashing too, maybe concurrency is causing these issues.

**Comment by preethamr** [comment]
Need to update config with new Linea RPC. @preethamr

**Comment by wanglonghong** [comment]
Automatically closed. reopening

**Comment by rhlsthrm** [comment]
New PR created and merged to manage cache better.

**Comment by rhlsthrm** [comment]
Still needs processing, lighthouse prover changes will help get this done.

**Comment by LayneHaber** [comment]
"blocked" by #4345 #4344

**Comment by preethamr** [comment]
The backlog has been cleared.
Pending messages distribution:
```
 count | origin_domain |              now
-------+---------------+-------------------------------
     3 | 2053862260    | 2023-06-08 02:03:13.064842+00
   103 | 9991          | 2023-06-08 02:03:13.064842+00
   ```
