### ISSUE TITLE
Chain Abstraction xMinter UI

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#4232]
## Background

A simplified Chain Abstraction UI example that showcases the usage of core SDK, CA SDK, and calling a CA adapter contract.

## Definition Of Done

This template should include a minimal UI that showcases a completed CA integration. It should:
- Be used as a reference for integrators when they start the CA integration flow and when we need to demonstrate the CA flow during onboarding calls
- Be forkable
- Include examples of using CA SDK to construct swapdata calls
- Include examples of using core SDK to estimate fees, calculate amount received, etc
- Be documented in the Chain Abstraction section of our docs

## Tasks

- [ ] UI should demonstrate pre- and post-CA integration flow for the end user (need to wireframe a design for this)
- [ ] Code should be clearly documented and show usage of the CA SDK (how to construct the swapdata)
- [ ] Code should be clearly documented and show usage of the core SDK (estimateRelayerFee, calculateAmountReceived, xcall, bumpTransfer?, updateSlippage?)
- [ ] Documentation in the style of a short walkthrough/guide for this template

**Comment by alexwhte** [comment]
**Complexity: 8**
  [See the discussion](https://action.parabol.co/meet/ne6bRdr87m/estimate/14) in Sprint Poker #​​36

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by rhlsthrm** [comment]
In progress, working on token list.

**Comment by prathmeshkhandelwal1** [comment]
https://www.notion.so/connext/Workshop-on-chain-abstraction-3220b374dcb24e4ba765dd7b8cb01f36

**Comment by sanchaymittal** [comment]
- friday demo for xMinterUI, alex and max will provide feedback soon. That will be taken care in next iteration, which will be a new task.
- As of now, contracts bug remains which will worked upon today.

**Comment by rhlsthrm** [comment]
This has been completed, but we are going to iterate on it in new issues/scope.
