### ISSUE TITLE
BNB AMB (BSC)

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4517]
pre-spec here: https://www.notion.so/connext/Pre-Spec-for-BSC-Amb-3578aea3d7a4485eb63498ece0b22fbd?pvs=4

**Chosen AMB for Bsc is Axelar**

Subtasks to be done:
**- Contracts** 
- [x] https://github.com/connext/monorepo/issues/4538

**- Subgraph**
- [x] https://github.com/connext/monorepo/issues/4544

**- Lighthouse**
- [x] https://github.com/connext/monorepo/issues/4545

- Testing 
- TODO: Need to define success criteria

**Comment by sanchaymittal** [comment]
all the issues are completed for this EPIC :tada
