### ISSUE TITLE
Offchain(Lighthouse) subtasks for BNB AMB

### ISSUE THREAD

**Issue by sanchaymittal** [connext/monorepo#4545]
- https://github.com/connext/monorepo/issues/4517
https://connext.notion.site/Pre-Spec-for-BSC-Amb-3578aea3d7a4485eb63498ece0b22fbd

## Action Items
- processFromRoot():  we don't need any task for bsc anymore, As Axelar doesn't need any transaction at destination.
- propogate & sendOutboundRoot::
- [x] implement relayer fee estimation (https://docs.axelar.dev/dev/axelarjs-sdk/axelar-query-api#estimategasfee)
- [x] encoding for the required params for the call to initiate `callContract()` and other params based on contract construction.
- [x] update unit test and write test for new shared functions

## Acceptance Criteria
- [ ] Run local env for testnet.
- [ ] Run local environment to complete to process the transfers stuck at mainnet.

**Comment by liu-zhipeng** [comment]
https://github.com/connext/monorepo/pull/4659
