### ISSUE TITLE
[internal] Pull data for OKRs

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#4579]
## Background

Measurements can be cool

### Linked Issues & Documentation

@alexwhte to add doc

## Definition Of Done

Data is pulled and presented

## Tasks

- [x] @LayneHaber to pull cost information
- [x] @just-a-node to pull integration metrics
- [x] @preethamr to pull retention metrics

**Comment by preethamr** [comment]
This is done.
