### ISSUE TITLE
Using Balancer V2 for gnosis swaps

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [connext/monorepo#4617]
## Background

We planned to use honeyswap initially for getting multi-swap paths for gnosis, But due to lack of proper honeyswap SDK to find the relevant information for swaps is difficult. 
Balancer has better liquidity and reliability for gnosis swaps.

### Linked Issues & Documentation

- List of linked issues, external links, etc

## Definition Of Done

Describes in 1-2 sentences what the output of the Task is, so that it can be verified by another team member easily. “Feature X is implemented as described and can be verified by using it”

## Tasks

- [ ] Creating balancer swapper contracts
- [ ] Adding swapper address to configs
- [ ] Add off-chain pieces in chain-abstraction SDK for balancer

**Comment by preethamr** [comment]
@just-a-node Do we need this still

**Comment by prathmeshkhandelwal1** [comment]
We still dont have gnosis swapper in chain-abstraction SDK. So yes we need it for making it work. But not sure if this aligns with our current priority.
