### ISSUE TITLE
Mainnet merge pending stability fixes 

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#4634]
## Background
We havent merged a lot of the stability changes from Testnet to prod yet

Merge to mainnet after many fixes.

### Linked Issues & Documentation

- List of linked issues, external links, etc

## Definition Of Done

Mainnet is merged and deployed.

## Tasks

- [ ] Verify ops.
- [ ] Collect final PRs to main.
- [ ] Merge to testnet-prod.
- [ ] Merge to prod.

**Comment by rhlsthrm** [comment]
Create release notes for changes.
