### ISSUE TITLE
Chain-abstraction UI 

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [connext/monorepo#4647]
### Problem
Continuation of completing https://chain-abstraction-reference.vercel.app/
See https://www.notion.so/connext/Workshop-on-chain-abstraction-3220b374dcb24e4ba765dd7b8cb01f36

### Proposed Solution
design refs https://www.figma.com/file/yNNcFlh0Nhm2oReRyHV2cq/Chain-Abstraction-reference?type=design&node-id=0%3A1&mode=design&t=zxu26UDVhQqOubeM-1

Done is more important than making the design look perfect since we just want to get in front of users. lmk if you have questions or need components clarified, and we can outsource this part if it's time consuming

filed the chain+asset selection modal to CH here #4670

### Acceptance criteria
- [ ] UI is able to be shown to prospective partners as a demo
- [ ] UI has features below
User can select asset+chain from any network supported
User can see fees, slippage, and estimated amount received
User can submit the action
Something happens on destination to demonstrate a contract being updated
ex/ Greeting
Improve previous iteration with suggested changes.

## Tasks

- [ ] Add display of greeting variable using providers
- [ ] Enhance UI

**Comment by rhlsthrm** [comment]
New repo created, in progress.

**Comment by prathmeshkhandelwal1** [comment]
New Repo: - https://github.com/connext/chain-abstraction-reference/tree/main

**Comment by rhlsthrm** [comment]
Coinhippo is done, will add to our component.

**Comment by rhlsthrm** [comment]
Coinhippo component didn't work, so we have to rebuild it internally. Expecting to be done by today.

**Comment by rhlsthrm** [comment]
Changed estimate based on scope increases.

**Comment by prathmeshkhandelwal1** [comment]
https://chain-abstraction-reference.vercel.app/

**Comment by prathmeshkhandelwal1** [comment]
Ready for test.
