### ISSUE TITLE
Protocol & backend tasks for integration test

### ISSUE THREAD

**Issue by wanglonghong** [connext/monorepo#4708]
## Background

Get both offchain/onchain ready for a successful test of upcoming op upgrading

## Tasks To Do

- [x] #4721
- [ ] #4718
- [ ] #4714
- [ ] Setup a separate database for dev-net. To decrease the sync time, we can basically copy/paste the data from Mainnet prod database.
- [ ] Setup 3rd party services as needed (cache, rabbitmq, etc).
- [ ] Setup cartographer agents and store the subgraph data in the dev-net database.
- [ ] Run offchain agents (router, sequencer, lighthouse, relayer, watcher, sdk server, etc)

**Comment by sanchaymittal** [comment]
init

**Comment by sanchaymittal** [comment]
- making progress on subgraph deployment
- discussing the strategy for contracts and state management

**Comment by rhlsthrm** [comment]
Moving back into monorepo, set up tenderly devnet with CLI. Working on deploying contracts including admin connectors.

**Comment by sanchaymittal** [comment]
closing this issue and moving tasks under epic #4713
