### ISSUE TITLE
Optimistic Roots v1.1

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#4713]
## Problem
Optimistic Roots v1.1 is a critical upgrade to reduce costs of messaging layer 

In order to launch optimistic roots, we are building an integration testing service. Until now, we have not had a controlled environment which we can use to test certain scenarios which are otherwise impractical to test on testnets/mainnets. 

## Impact
Reduces costs by est. >90%
This increases Connext runway and significantly improves our ability to expand to new chains. 
This is important for Connext developers to test upcoming protocol upgrades in isolation.

## Proposed Solution
Reference: https://www.notion.so/connext/spec-Integration-Tester-Environment-7a21670935ef44b9a4091b633a11164e
NEW (Oct) v1.1 spec https://www.notion.so/Tech-Doc-v1-1-a4c3581aace64a08a2fc8963314a1a03?pvs=46&qid=
Test case scenarios draft https://www.notion.so/defi-wonderland/v1-Test-case-scenarios-41ee8d9525a648bd8f817ad222c7580d

V1 Off-Chain Spec: https://www.notion.so/connext/Optimistic-Roots-Off-Chain-65df2c53dc2943aab73f3ea646057ea0

See all the tasks in epic below

## Acceptance Criteria
- [x] V1 contracts are deployed on staging
- [x] V1 subgraph changes are deployed on staging
- [x] V1 works in slow mode
- [x] V1 works in op-mode
- [x] V1.1 contracts are deployed on staging
- [x] V1.1 subgraph changes are deployed on staging
- [x] V1.1 works in slow mode
- [x] V1.1 works in op-mode
- [x] V1.1 works in mixed modes
- [x] V1.1 Watcher (DW) can detect fraud and switch to slow mode
- [x] V1.1 works when switching back and forth between op-mode and slow mode

**Comment by alexwhte** [comment]
@preethamr pls create final issues and add to epic

**Comment by alexwhte** [comment]
https://www.notion.so/defi-wonderland/v1-Test-case-scenarios-41ee8d9525a648bd8f817ad222c7580d
Test case scenarios draft

**Comment by preethamr** [comment]
This Epic was completed.
