### ISSUE TITLE
[router/sequencer] Implement sweepable amounts in bids

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#4720]
## Background

Routers won't bid unless evenly divisible. Need to implement changes to allow bids for remainders in the same way we do onchain: https://github.com/connext/monorepo/blob/4c057678966204b0f65dfd2d63acd4b6f051ca67/packages/deployments/contracts/contracts/core/connext/facets/BridgeFacet.sol#L904-L916

## Definition Of Done

Routers will bid on amounts if not evenly divisible

## Tasks

- [ ] Implement in router bid
- [ ] Implement in sequencer selection
- [ ] Publish new offchain versions

**Comment by alexwhte** [comment]
closing for #4685
