### ISSUE TITLE
Set up additional agents

### ISSUE THREAD

**Issue by wanglonghong** [connext/monorepo#4749]
## Background
To test everything in e2e, we should add watcher and sdk-server agents to the checklist and create a testing plan for both.

## Tasks

- [ ] Set up watcher
- [ ] Set up sdk-server
- [ ] Create a testing plan for both.
