### ISSUE TITLE
BTRST Token verification (xERC20)

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [connext/monorepo#4750]
## Background

https://github.com/connext/chaindata/pull/81/files
https://github.com/connext/monorepo/pull/4719/files

### Linked Issues & Documentation

- List of linked issues, external links, etc

## Definition Of Done

Verification of above PR according to this list.
https://www.notion.so/connext/78985132bc9e4a9f978b2bd5ea20d0c9?v=ba7ff8897cf741ce93ef8e523a640486&pvs=4

**Comment by prathmeshkhandelwal1** [comment]
### Per-Whitelist Checklist

- [ ]  Double checked information with team with understanding we CANNOT undo once live easily
    - [ ]  Verified PR against chaindata maps. Each supported chain must:
        - [ ]  Includes decimals
        - [ ]  Includes symbol
        - [ ]  Includes mainnet equivalent
    - [ ]  Verified PR against monorepo maps
- [ ]  Verify the token exists at the indicated chain / address configuration
- [ ]  Verify the token source is verified on the explorers
- [ ]  Verify the canonical decimals are correct (these CANNOT) change without us needing to remove the asset
- [ ]  Verify the name is correct (our local asset will have the name `next${CONFIG_NAME}`
- [ ]  Verify the asset is constant-supply
- [ ]  Verify the contract is not-upgradeable
    
    **************NOTE:************** Sometimes this is unavoidable, ensure the listing team understands that changes to decimals, supply logic, or minting/burning rights will cause people to lose funds in the execution layer.
    
- [ ]  **SAFETY CHECKS**
    - [ ]  Ensure no duplicate `adopted` asset
    - [ ]  Ensure no duplicate `local` asset
    - [ ]  Ensure no duplicate `canonical` hash (duplicate domain and id)
- [ ]  Checkout branch from PR and perform a dry-run transaction by setting the `apply` flag to false:
    
    ```bash
    yarn workspace @connext/smart-contracts initialize --name "assets" --network "testnet" --env "production" --apply "false"
    ```
    
    Gather the data, and put through tenderly simulator to ensure the whitelist transaction will not fail.
    
- [ ]  Propose the transaction using information posted in dry-run and safe transaction builder, or by running the `initialize` script with `apply` flag as true. If there is a `local` asset, `setupWithDeployedRepresentation` will be used, otherwise `setupAsset` is called.
- [ ]  Test a slow-path transaction
    
    ************NOTE:************ Adding router-liquidity will be difficult to undo because it requires the proper mapping
    
- [ ]  Ensure slow-path transaction looks okay to requesting team
- [ ]  Vibe 🆒 🕶️

**Comment by prathmeshkhandelwal1** [comment]
Their contracts are not verified on the explorers

**Comment by prathmeshkhandelwal1** [comment]
ChainData verified, seems correct

**Comment by prathmeshkhandelwal1** [comment]
We dont have proper communication with them, they have submitted the PR for whitelisting, And the whitelisting is done.

They havent send their test token yet, so waiting on that.

**Comment by prathmeshkhandelwal1** [comment]
Asked them to create UI PR's as well
