### ISSUE TITLE
Gelato xTokens

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [connext/monorepo#4804]
## Background

Create a POC for gelato tokens

## Definition Of Done

XTokens working on testnet UI.

## Tasks

- [ ] Create erc20 gelato tokens
- [ ] Create xerc20 gelato tokens
- [ ] Create lockbox
- [ ] Create adapter
- [ ] Intgerate with testnet UI

**Comment by sanchaymittal** [comment]
in progress:
- polygon deployment 
- integration in testnet ui

**Comment by sanchaymittal** [comment]
- listing of xtoken and adding the pr to UI

**Comment by sanchaymittal** [comment]
- waiting for the response from gelato
- @prathmeshkhandelwal1 add the issue we are facing currently

**Comment by prathmeshkhandelwal1** [comment]
- their tokens required seperate allowance for burn functionality. and our scripts are not designed for that

**Comment by sanchaymittal** [comment]
- waiting for the call to schedule.

**Comment by sanchaymittal** [comment]
- shared an update about the burn mechanism at xERC20, reviewing it internally.

**Comment by just-a-node** [comment]
Reach back out in Q1 2024 with updated burn changes.

**Comment by preethamr** [comment]
@just-a-node Should we reach back to them now?

**Comment by prathmeshkhandelwal1** [comment]
They wanted `burnFrom` in xERC20 contracts instead of `burn`. I dont think we aligned to do those changes. So I wont be very sure about reaching back to them. Maybe we can ask BD team for this
