### ISSUE TITLE
EURe xToken

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#4806]
## Background

Create a POC for EURe tokens

## Definition Of Done

XTokens working on testnet UI.

## Tasks

- [ ] Create erc20 EURe tokens
- [ ] Create xerc20 EURe tokens
- [ ] Create lockbox
- [ ] Create adapter
- [ ] Intgerate with testnet UI

**Comment by sanchaymittal** [comment]
done and dusted
