### ISSUE TITLE
Deploy TVOTES test contract to mainnets

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#4853]
## Background

Need to run a prod-like test on mainnets.

Requires:
- [x] `TestVotes` whitelisted on all testnet chains
- [x] `TestVotes` deployed to mainnets (mainnet, arbitrum, optimism, gnosis, polygon, bnb)
- [x] `TestVotes` liquidity added to router
- [x] `TestVotes` whitelist transactions proposed on mainnet

The `TestVotes` contract to use can be found in PR https://github.com/connext/monorepo/pull/4706

### Linked Issues & Documentation

- https://github.com/connext/monorepo/pull/4706

**Comment by LayneHaber** [comment]
To deploy the token on that branch:

```
yarn workspace @connext/smart-contracts hardhat deploy --tags "Utils" --network <NETWORK>
```

To generate whitelist transactions:

```
yarn workspace @connext/smart-contracts initialize --name "assets" --asset "<NAME_IN_CONFIG>" --apply "false" --domains "DOMAIN_1" "DOMAIN_2" ...
```

**Comment by just-a-node** [comment]
@rhlsthrm Asset setup datas for multisig:

```
REGISTER ASSETS
        Verifying asset setup for TVOTES (0x53cA5b3D36a06D7432098e9AFc22F39C4848516A). Canonical ID: 0x00000000000000000000000053ca5b3d36a06d7432098e9afc22f39c4848516a; Canonical Domain: 6648936; Key: 0xe70f8a39253700d3d0f2fbe9b287dfab064c72cc714e1dadafa9be9e8b0bee8e
[1           ] [0x8898B..e63C6] {Connext} .canonicalToAdopted(bytes32)(0xe70f8a39253700d3d0f2fbe9b287dfab064c72cc714e1dadafa9be9e8b0bee8e) : undefined
[1           ] [0x8898B..e63C6] {Connext} .setupAsset(6648936,0x00000000000000000000000053ca5b3d36a06d7432098e9afc22f39c4848516a,18,nextTVOTES,nextTVOTES,0x53cA5b3D36a06D7432098e9AFc22F39C4848516A,0x0000000000000000000000000000000000000000,10000000000000000000000000) : {"to":"0x8898B472C54c31894e3B9bb83cEA802a5d0e63C6","chain":1,"data":"0xb64a5e07000000000000000000000000000000000000000000000000000000000065746800000000000000000000000053ca5b3d36a06d7432098e9afc22f39c4848516a00000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000014000000000000000000000000053ca5b3d36a06d7432098e9afc22f39c4848516a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000084595161401484a000000000000000000000000000000000000000000000000000000000000000000000a6e65787454564f54455300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a6e65787454564f54455300000000000000000000000000000000000000000000"}
Failed to lookup canonical to adopted, or remove asset: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="canonicalToAdopted(bytes32)", data="0xc319947e", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
[56          ] [0xCd401..4F2CE] {Connext} .canonicalToAdopted(bytes32)(0xe70f8a39253700d3d0f2fbe9b287dfab064c72cc714e1dadafa9be9e8b0bee8e) : undefined
[56          ] [0xCd401..4F2CE] {Connext} .setupAssetWithDeployedRepresentation(6648936,0x00000000000000000000000053ca5b3d36a06d7432098e9afc22f39c4848516a,0xDF97CadbcCeE9cfdB12A3e9BB7663E6753A71a0C,0xDF97CadbcCeE9cfdB12A3e9BB7663E6753A71a0C,0x0000000000000000000000000000000000000000) : {"to":"0xCd401c10afa37d641d2F594852DA94C700e4F2CE","chain":56,"data":"0xe1cb3958000000000000000000000000000000000000000000000000000000000065746800000000000000000000000053ca5b3d36a06d7432098e9afc22f39c4848516a000000000000000000000000df97cadbccee9cfdb12a3e9bb7663e6753a71a0c000000000000000000000000df97cadbccee9cfdb12a3e9bb7663e6753a71a0c0000000000000000000000000000000000000000000000000000000000000000"}
Failed to lookup canonical to adopted, or remove asset: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0xade09131C6f43fe22C2CbABb759636C43cFc181e","to":"0x5bB83e95f63217CDa6aE3D181BA580Ef377D2109","data":"0x2c1999d0e70f8a39253700d3d0f2fbe9b287dfab064c72cc714e1dadafa9be9e8b0bee8e","accessList":null}, error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32015,\"message\":\"VM execution error.\",\"data\":\"Reverted 0xc319947e\"},\"id\":45}","error":{"code":-32015,"data":"Reverted 0xc319947e"},"requestBody":"{\"method\":\"eth_call\",\"params\":[{\"from\":\"0xade09131c6f43fe22c2cbabb759636c43cfc181e\",\"to\":\"0x5bb83e95f63217cda6ae3d181ba580ef377d2109\",\"data\":\"0x2c1999d0e70f8a39253700d3d0f2fbe9b287dfab064c72cc714e1dadafa9be9e8b0bee8e\"},\"latest\"],\"id\":45,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://rpc.ankr.com/gnosis"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[100         ] [0x5bB83..D2109] {Connext} .canonicalToAdopted(bytes32)(0xe70f8a39253700d3d0f2fbe9b287dfab064c72cc714e1dadafa9be9e8b0bee8e) : undefined
[100         ] [0x5bB83..D2109] {Connext} .setupAssetWithDeployedRepresentation(6648936,0x00000000000000000000000053ca5b3d36a06d7432098e9afc22f39c4848516a,0x8B988a5e3C1C7f5230102606EAeFe421e2CD9A10,0x8B988a5e3C1C7f5230102606EAeFe421e2CD9A10,0x0000000000000000000000000000000000000000) : {"to":"0x5bB83e95f63217CDa6aE3D181BA580Ef377D2109","chain":100,"data":"0xe1cb3958000000000000000000000000000000000000000000000000000000000065746800000000000000000000000053ca5b3d36a06d7432098e9afc22f39c4848516a0000000000000000000000008b988a5e3c1c7f5230102606eaefe421e2cd9a100000000000000000000000008b988a5e3c1c7f5230102606eaefe421e2cd9a100000000000000000000000000000000000000000000000000000000000000000"}
Failed to lookup canonical to adopted, or remove asset: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="canonicalToAdopted(bytes32)", data="0xc319947e", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
[42161       ] [0xEE9de..C24C8] {Connext} .canonicalToAdopted(bytes32)(0xe70f8a39253700d3d0f2fbe9b287dfab064c72cc714e1dadafa9be9e8b0bee8e) : undefined
[42161       ] [0xEE9de..C24C8] {Connext} .setupAssetWithDeployedRepresentation(6648936,0x00000000000000000000000053ca5b3d36a06d7432098e9afc22f39c4848516a,0x008B59Ff5364045337994c00eFc7aD1c562bB629,0x008B59Ff5364045337994c00eFc7aD1c562bB629,0x0000000000000000000000000000000000000000) : {"to":"0xEE9deC2712cCE65174B561151701Bf54b99C24C8","chain":42161,"data":"0xe1cb3958000000000000000000000000000000000000000000000000000000000065746800000000000000000000000053ca5b3d36a06d7432098e9afc22f39c4848516a000000000000000000000000008b59ff5364045337994c00efc7ad1c562bb629000000000000000000000000008b59ff5364045337994c00efc7ad1c562bb6290000000000000000000000000000000000000000000000000000000000000000"}
Failed to lookup canonical to adopted, or remove asset: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="canonicalToAdopted(bytes32)", data="0xc319947e", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
[10          ] [0x8f749..5DEDA] {Connext} .canonicalToAdopted(bytes32)(0xe70f8a39253700d3d0f2fbe9b287dfab064c72cc714e1dadafa9be9e8b0bee8e) : undefined
[10          ] [0x8f749..5DEDA] {Connext} .setupAssetWithDeployedRepresentation(6648936,0x00000000000000000000000053ca5b3d36a06d7432098e9afc22f39c4848516a,0x60e391DBB9B3a324d8fE1e7d8047A98D0619Cd2B,0x60e391DBB9B3a324d8fE1e7d8047A98D0619Cd2B,0x0000000000000000000000000000000000000000) : {"to":"0x8f7492DE823025b4CfaAB1D34c58963F2af5DEDA","chain":10,"data":"0xe1cb3958000000000000000000000000000000000000000000000000000000000065746800000000000000000000000053ca5b3d36a06d7432098e9afc22f39c4848516a00000000000000000000000060e391dbb9b3a324d8fe1e7d8047a98d0619cd2b00000000000000000000000060e391dbb9b3a324d8fe1e7d8047a98d0619cd2b0000000000000000000000000000000000000000000000000000000000000000"}
Failed to lookup canonical to adopted, or remove asset: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="canonicalToAdopted(bytes32)", data="0xc319947e", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
[137         ] [0x11984..F2259] {Connext} .canonicalToAdopted(bytes32)(0xe70f8a39253700d3d0f2fbe9b287dfab064c72cc714e1dadafa9be9e8b0bee8e) : undefined
[137         ] [0x11984..F2259] {Connext} .setupAssetWithDeployedRepresentation(6648936,0x00000000000000000000000053ca5b3d36a06d7432098e9afc22f39c4848516a,0xA6fc0c22ca188970152fcb00Ac3646d278fb5188,0xA6fc0c22ca188970152fcb00Ac3646d278fb5188,0x0000000000000000000000000000000000000000) : {"to":"0x11984dc4465481512eb5b777E44061C158CF2259","chain":137,"data":"0xe1cb3958000000000000000000000000000000000000000000000000000000000065746800000000000000000000000053ca5b3d36a06d7432098e9afc22f39c4848516a000000000000000000000000a6fc0c22ca188970152fcb00ac3646d278fb5188000000000000000000000000a6fc0c22ca188970152fcb00ac3646d278fb51880000000000000000000000000000000000000000000000000000000000000000"}
```

**Comment by just-a-node** [comment]
Added 1000 TVOTES router liquidity to all mainnet chains.
