### ISSUE TITLE
Lockbox deposit when adding router liquidity 

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#4864]
## Background

Adding router liquidity with an asset that has a lockbox on a given chain should be able to take automatically deposit and add liquidity instead of having to manually deposit into the lockbox first.

### Linked Issues & Documentation

- List of linked issues, external links, etc

## Definition Of Done

User can deposit router liquidity in canonical asset.

## Tasks

- [ ] Check if deposit is being made with an asset that has a lockbox on the given chain
- [ ] Create txn for user to deposit into the lockbox
- [ ] Create txn for user to addRouterLiquidity using the delivered xAsset
