### ISSUE TITLE
[Connextscan] Add deposit/withdraw utility for Lockbox

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#4865]
## Background

For assets that have a Lockbox, router liquidity providers must be able to:
- deposit into the Lockbox before adding router liquidity
- withdraw from the Lockbox after removing router liquidity

An asset follows this pattern if:
- `is_xERC20` is `true` for the top-level asset config
-  for a particular chain, the asset has an `xERC20` and a `lockbox` field

Example where NEXT on mainnet ETH is a Lockbox asset.
```
  {
    "id": "next",
    "symbol": "NEXT",
    "name": "Connext",
    "image": "/logos/assets/next.png",
    "is_xERC20": true,
    "contracts": [
      {
        "contract_address": "0xFE67A4450907459c3e1FFf623aA927dD4e28c67a",
        "chain_id": 1,
        "decimals": 18,
        "symbol": "NEXT",
        "xERC20": "0x58b9cB810A68a7f3e1E4f8Cb45D1B9B3c79705E8",
        "lockbox": "0x22f424Bca11FE154c403c277b5F8dAb54a4bA29b",
        "lockbox_adapter": "0x222051df1632517e2008ca65cffcb0466cb3828d"
      },
      {
        "contract_address": "0x58b9cB810A68a7f3e1E4f8Cb45D1B9B3c79705E8",
        "chain_id": 137,
        "decimals": 18
      },
      {
        "contract_address": "0x58b9cB810A68a7f3e1E4f8Cb45D1B9B3c79705E8",
        "chain_id": 10,
        "decimals": 18
      },
      {
        "contract_address": "0x58b9cB810A68a7f3e1E4f8Cb45D1B9B3c79705E8",
        "chain_id": 42161,
        "decimals": 18
      },
      {
        "contract_address": "0x58b9cB810A68a7f3e1E4f8Cb45D1B9B3c79705E8",
        "chain_id": 100,
        "decimals": 18
      }
    ],
    "color": "#4243d0"
  },
```

For assets that qualify, add a deposit/withdraw utility to their "Manager Router Liquidity" page (maybe in another border box that shows up above the existing asset select):

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcmRuIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5f859d3a66863a15d2ccfbc88b6d50bb8b23ca01/image.png)

This is similar to wrapping/unwrapping WETH. Users can either `deposit` to or `withdraw` from the Lockbox contract. When depositing, users send the `contract_address` (ERC20) and receive the `xERC20`. Vice versa for withdrawing.

### Linked Issues & Documentation

- List of linked issues, external links, etc

## Definition Of Done

Utility for deposit/withdraw exists in the "Manage Router Liquidity" modal for assets that qualify as Lockbox assets.

## Tasks

- [ ] Check if the selected asset is a Lockbox asset, if yes, do the following:
- [ ] In the "Add" router liquidity tab: show the "Deposit to Lockbox" utility and make it clear that the xERC20 is used to add liquidity
- [ ] In the "Remove" router liquidity tab: show the "Withdraw from Lockbox" utility and make it clear that the user will receive xERC20 after removing router liquidity and that they can withdraw ERC20 using xERC20
- [ ] Show balances of the xERC20 and ERC20 (sometimes they have the same symbol like NEXT/NEXT, so label them accordingly).
- [ ] Last related thing is to make sure we show the balance of the xERC20 for Lockbox assets in the Routers Liquidity page:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcmhuIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b4d693f42bb902a36d95863ac72eefe5387cfb10/image.png)
