### ISSUE TITLE
Connext on L2Beat

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#4929]
## Background

Submit PR to update Connext data on the bridge dashboard.

## Tasks

- [ ] Add USDT and DAI
- [ ] Change the Website link that currently points to our blog to https://connext.network/
- [ ] Request to update wording: "Funds can be stolen if connectors to optimistic rollups (Optimism, Arbitrum) receive a fraudulent message within 7-day fraud-proof window." ->  "Funds can be stolen if connectors to optimistic rollups (Optimism, Arbitrum) receive a fraudulent message within 7-day fraud-proof window AND fraud is not detected by watchers"

**Comment by maxlomu** [comment]
Would be good to also add

- Confirm TVL for all chains and all assets
- Change wording on the type of bridge (we are not just a liquidity network anymore)

**Comment by alexwhte** [comment]
we need to update teh connector itself, it's not jut updating on their website
