### ISSUE TITLE
Custom XERC20 Multisend

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#4930]
## Background

Write and deploy a custom Multisend contract that combines Lockbox deposit and xcall together. This enables single txn bridging of xERC20s that have a lockbox on the source chain but would be specific to Connext.

## Tasks

- [ ] Write XERC20Multisend.sol
- [ ] Write unit tests
- [ ] Deploy to all chains using existing hardhat deploy utils setup

**Comment by just-a-node** [comment]
Wait until we get feedback from users to do this.

**Comment by just-a-node** [comment]
This will be tackled in the bridge adapter.
