### ISSUE TITLE
Whitelist ALCX mainnet

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#4931]
## Background

Whitelist ALCX on mainnet.

## Definition Of Done

ALCX whitelisted.

## Tasks

- [x] PR to monorepo config
- [x] PR to chaindata
- [x] PRs to bridge UI / connextscan
- [x] Execute whitelisting via admin multisig
- [ ] Test slow path bridge, fast path bridge
