### ISSUE TITLE
FRACTION whitelisting

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [connext/monorepo#4958]
## Background

Whitelist FRACTION for the mainnet.

### Linked Issues & Documentation

- List of linked issues, external links, etc

## Definition Of Done

Describes in 1-2 sentences what the output of the Task is, so that it can be verified by another team member easily. “Feature X is implemented as described and can be verified by using it”

## Tasks

- [x] FRACTION mainnet whitelisted
- [x] FRACTION lockbox adapter deployed
- [x] FRACTION UI updates completed
- [x] FRACTION slow path tested
- [x] FRACTION router liquidity added, fast path tested

**Comment by sanchaymittal** [comment]
- we are waiting for them to proceed with verification on contracts and then give connext the minting & burn right on mainnet.

**Comment by prathmeshkhandelwal1** [comment]
- Have to verify there contracts to proceed
