### ISSUE TITLE
XOC - Stuck Tx 

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [connext/monorepo#4961]
## Background

We need to relist XOC with bogus domain, as there is multiple minters for them.

Also to relist we need to unstuck the in-flight tx first, and then update the cap to `0`. to bridge out all the funds.
https://connextscan.io/tx/0x86a3ed92b1d0cd68632741e978c39f16e6ae44056299b396891c3c64b9c38ec4

### Linked Issues & Documentation

- List of linked issues, external links, etc

## Definition Of Done

Describes in 1-2 sentences what the output of the Task is, so that it can be verified by another team member easily. “Feature X is implemented as described and can be verified by using it”

## Tasks

- [x] XOC plugs 509 on polygon
- [x] Set cap to 0, get txn unstuck
- [x] Re-register XOC with pseudo-canonical domain

**Comment by sanchaymittal** [comment]
- we are waiting on XOC tokens.

**Comment by prathmeshkhandelwal1** [comment]
- They have inited the tx, its a multisig so from there end it may take few days

**Comment by just-a-node** [comment]
Funds executed, waiting for liquidity cap update (need Connext signers)
