### ISSUE TITLE
Staging slow paths should work

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#4975]
## Problem
`staging` env with op-roots V1 should work, both in slow-mode and op-mode

## Impact
This is a must have before we can qualify V1 and deploy it to mainnet

## Proposed Solution
Manually test and ensure each supported chain, works in both op-mode and slow-mode.
Deploy fixes to `staging` as necessary to resolve any errors.

## Acceptance Criteria
These sub tasks need to be completed
- [x] https://github.com/connext/monorepo/issues/4969
- [ ]  https://github.com/connext/monorepo/issues/4968
- [ ]  https://github.com/connext/monorepo/issues/4970
- [ ]  https://github.com/connext/monorepo/issues/4971
- [ ]  https://github.com/connext/monorepo/issues/4972
- [ ]  https://github.com/connext/monorepo/issues/4973
- [ ]  https://github.com/connext/monorepo/issues/4974

**Comment by sanchaymittal** [comment]
This should be an epic @preethamr 
cc: @alexwhte

**Comment by alexwhte** [comment]
Closing, the real goal is to launch optimistic roots so combining them
