### ISSUE TITLE
Integration Tests

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#5001]
## Problem
Need automation of integration tests for Optimistic Roots v1.1

In order to launch optimistic roots, we are building an integration testing service. Until now, we have not had a controlled environment which we can use to test certain scenarios which are otherwise impractical to test on testnets/mainnets. 

## Impact
Integration Tests for Optimistic Roots v1.1 is a key to reduce regression, and increase development velocity

## Proposed Solution
https://github.com/connext/monorepo/tree/main/packages/integration#integration
Reference: https://www.notion.so/connext/spec-Integration-Tester-Environment-7a21670935ef44b9a4091b633a11164e
NEW (Oct) v1.1 spec https://www.notion.so/Tech-Doc-v1-1-a4c3581aace64a08a2fc8963314a1a03?pvs=46&qid=

See all the tasks in epic below

## Acceptance Criteria
- [x] Create scripts to spin up infrastructure against Tenderly devnets from a single config file.
- [x] Create CLI to run the infra scripts.
- [ ] Create a test script to run a configurable amount of transfers.
- [ ] Add functionality to CLI to run the tests.
- [ ] Spec out additional tests needed for op roots (Defi Wonderland)
- [x] Run offchain agents (router, sequencer, lighthouse, relayer, watcher, sdk server, etc) 
  - [x] Cartographer
  - [x] Relayer
  - [x] Sequencer
  - [x] Router
  - [x] Lighthouse
  - [ ] Watcher
  - [ ] SDK server
- [ ] Complete tasks in this epic
