### ISSUE TITLE
FIx xERC20 repo deploy script

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [connext/monorepo#5035]
## Background

Currently deploying new xERC20 and lockbox from [xERC20](https://github.com/connext/xERC20) repo, deploys a new factory contract everytime. So we have to deploy a universal factory both for upgradable and non-upgradable xERC20s

## Definition Of Done

Both factory's get deployed on every chain.

## Tasks

- [x] Deploy upgradable xERC20 factory  
- [x] Deploy non-upgradable xERC20 factory (Not valid anymore)
- [x] Fix script to use those address, rather than deploying new address.
- [ ] Add verification for multichain deployment.
