### ISSUE TITLE
Test whitelisting of xtoken with new Post-Audit changes

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [connext/monorepo#5045]
## Background

We got new post audit changes in xERC20 repo. Which includes features like `burnFrom` and others. 

### Linked Issues & Documentation

- List of linked issues, external links, etc

## Definition Of Done

Create a new xERC20 token with new changes, and whitelist it using new domains.

## Tasks

- [x] Create new xERC20s on testnet
- [x] Whitelist it using old script.
- [x] Check if bridging is working

**Comment by prathmeshkhandelwal1** [comment]
tx pending, have to check what's the issue there.
https://testnet.connextscan.io/tx/0x287d72f2709dbf5b0ce76fc741c25bffbaf4b305ba8a1ed56a56b0e550aab49f

**Comment by sanchaymittal** [comment]
- fixing linea on test net should fix this.
- @sanchaymittal to fix linea on testnet.

**Comment by prathmeshkhandelwal1** [comment]
https://testnet.connextscan.io/tx/0x287d72f2709dbf5b0ce76fc741c25bffbaf4b305ba8a1ed56a56b0e550aab49f

Should we close this out as its done now.  @sanchaymittal Tagged you in discord chat for update on this.
