### ISSUE TITLE
Grumpycat Mainnet xERC20 Whitelisting

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#5047]
## Token Details
- Name: xGrumpy Cat
- Symbol: xGrumpyCat
- Chains: Ethereum, Optimism, Arbitrum, Polygon, BSC

## Tasks
- [x] PR to chaindata: _\<link to PR\>_
- [x] PR to monorepo allowlist config: https://github.com/connext/monorepo/pull/5046
- [x] Whitelisting complete: https://etherscan.io/tx/0x823e051b53e81e1731f4f84d3ee9b69ed096820925f1e733cca2294b3a849ceb, https://polygonscan.com/tx/0x80f1c0192306f34e6d43ffa3fa1221bf0c9718d4e3deb75667596344e5ed015d, https://bscscan.com/tx/0x82b81e3b208e60180f0ba0db6cbc59622258b09cf277d0094b00f21b57c67931, https://optimistic.etherscan.io/tx/0x6dde08d9bb667056c7118c1472ec44fc9eacce91ffe2229355aa7ae35bc42b14, https://arbiscan.io/tx/0x11b3c8d5c860c103032cd6fb451b6729a75eea625454ad436a4fefdfa6c31719
- [x] PR to Bridge UI: https://github.com/CoinHippo-Labs/connext-bridge/pull/222
- [x] PR to Connextscan: https://github.com/CoinHippo-Labs/connextscan-ui/pull/113
- [x] Lockbox Adapter deployed: https://etherscan.io/tx/0x338202b124f145c8b75c2a3bedf1626a29e7226beea2f39844cf5fb1f7618373
- [x] Slow path tested: https://connextscan.io/tx/0x837f8c78a4fa79985bb6ac96398ebfe62b18e1522a78082314b7b02e362ec51f, https://connextscan.io/tx/0x4b7acc89a22115347191f73dcb172be849e02d3f87fe2042a5790582f834db87, https://connextscan.io/tx/0x126acbad15f38ff194002aba315de0da97d368190aa7fd2c282b94a953616110, https://connextscan.io/tx/0x1dcbd6fc4ef18e2943e7bb1fda2052bfb774a7c4b6e2281e1a5b51c7ef143cc2
- [ ] Router liquidity added and fast path tested: _\<link to transfer(s)\>_

**Comment by sanchaymittal** [comment]
- No one hosting router, no need to complete the last step.
