### ISSUE TITLE
MIVA Mainnet xERC20 Whitelisting

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#5050]
## Token Details

- Name: Minerva
- Symbol: MIVA
- - Chains: Gnosis, Polygon

## Tasks

- [ ] PR to chaindata: _\<link to PR\>_
- [ ] PR to monorepo allowlist config: _\<link to PR\>_
- [ ] Whitelisting complete: _\<link to transaction(s)\>_
- [ ] PR to Bridge UI: _\<link to PR\>_
- [ ] PR to Connextscan: _\<link to PR\>_
- [ ] Lockbox Adapter deployed: _\<link to transaction(s)\>_
- [ ] Slow path tested: _<link to transfer(s)>_
- [ ] Router liquidity added and fast path tested: _\<link to transfer(s)\>_

**Comment by preethamr** [comment]
@just-a-node could we close this, since it is already whitelisted
