### ISSUE TITLE
IXT Mainnet xERC20 Whitelisting

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#5072]
## Token Details

- Name: IXT
- Symbol: IXT
- Chains: Ethereum, Optimism, Arbitrum, Polygon, Gnosis, BSC

## Tasks

- [ ] PR to chaindata: _\<link to PR\>_
- [x] PR to monorepo allowlist config: https://github.com/connext/monorepo/pull/5115/files
- [x] Whitelisting complete: _\<link to transaction(s)\>_
- [x] PR to Bridge UI: _\<link to PR\>_
- [x] PR to Connextscan: _\<link to PR\>_
- [x] Lockbox Adapter deployed: _\<link to transaction(s)\>_
- [x] Slow path tested: _<link to transfer(s)>_
- [ ] Router liquidity added and fast path tested: _\<link to transfer(s)\>_

**Comment by prathmeshkhandelwal1** [comment]
- Whitelisting calldata generated, going on with multisig
