### ISSUE TITLE
Deprecate Arb-goerli from staging and testnet-prod

### ISSUE THREAD

**Issue by sanchaymittal** [connext/monorepo#5161]
**Describe the Task**

Need to deprecate Arb-goerli from Staging and Testnet-prod as Arbitrum will discontinue it's support from 18th nov.

**Tasks**
- [x] remove domain from rootmanager - @liu-zhipeng 
- [x] remove config of arb goreli from staging and testnet prod - @just-a-node 
- [x] remove from SDK - @just-a-node 
- [x] remove from UI

**Comment by alexwhte** [comment]
needs to happen before friday

**Comment by liu-zhipeng** [comment]
https://goerli.etherscan.io/tx/0xc112339c61e1d60790b8e3b04ded565ba0a7b807a67792c18dbd47d8c0dfea6b
https://goerli.etherscan.io/tx/0x59c6490db9418dea3f5735f7d3ddaeaa28750558e7cd1c8ba32b2c266c9cb77c

Arb-goerli connector removed from staging and testnet-prod

**Comment by just-a-node** [comment]
We actually don't need changes to sdk. Should just remove arb-goerli artifacts from the `contracts` package eventually but removal of the connector will already suffice.

**Comment by preethamr** [comment]
https://github.com/connext/monorepo/pull/5195
https://github.com/connext/monorepo/pull/5196

**Comment by just-a-node** [comment]
https://github.com/CoinHippo-Labs/connextscan-ui/pull/123
https://github.com/CoinHippo-Labs/connext-bridge/pull/240

**Comment by preethamr** [comment]
Completed.
