### ISSUE TITLE
URUS Mainnet xERC20 Whitelisting

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#5191]
## Token Details

- Name: Aurox Token
- Symbol: URUS
- Chains: Ethereum, BSC

## Tasks

- [x] PR to chaindata: https://github.com/connext/chaindata/pull/103/files
- [x] PR to monorepo allowlist config: https://github.com/connext/monorepo/pull/5141
- [x] Whitelisting complete: https://app.safe.global/transactions/tx?id=multisig_0xf2964cCcB7CDA9e808aaBe8DB0DDDAF7890dd378_0x6b5fe95c34f7727bdaef647cb08107b331d71036f9e20d6b3db6040a2613074c&safe=eth:0xf2964cCcB7CDA9e808aaBe8DB0DDDAF7890dd378, https://app.safe.global/transactions/tx?id=multisig_0x06D63fb4f3F9B8235E71ff4AE82958a45B3dd4A8_0x82123d742b89a0180087df90d3635c8ba198470a536235f8fd272d6f9d2dfd16&safe=bnb:0x06D63fb4f3F9B8235E71ff4AE82958a45B3dd4A8
- [x] PR to Bridge UI: https://github.com/CoinHippo-Labs/connext-bridge/pull/232
- [x] PR to Connextscan: https://github.com/CoinHippo-Labs/connextscan-ui/pull/121
- [x] Lockbox Adapter deployed: https://etherscan.io/tx/0x87fda368b2d444618683b185d15121ef945f27a6fc8e7940ec70d4197c279fd5
- [x] Slow path tested: https://connextscan.io/tx/0x4b11b7c7c812a87182e5f46be6301dd213cb0d9f5c07d8ab881183a808035bf3
- [x] Router liquidity added and fast path tested: https://connextscan.io/tx/0x294d8810beaac63920c13de912edce2e8b4573927083ef93aed23d0c8a231f14, https://connextscan.io/tx/0x8e169a9ca0b842bb035199e9135de522e53e0374034e41d93d07453e8b0a2dac
