### ISSUE TITLE
SPACE Mainnet xERC20 Whitelisting

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#5209]
## Token Details

- Name: Space Token
- Symbol: SPACE
- Chains: Ethereum, Optimism, Arbitrum, Polygon, Gnosis, BSC

## Tasks

- [x] PR to chaindata: https://github.com/connext/chaindata/pull/108
- [x] PR to monorepo allowlist config: https://github.com/connext/monorepo/pull/5206
- [x] Whitelisting complete: https://app.safe.global/transactions/tx?id=multisig_0xf2964cCcB7CDA9e808aaBe8DB0DDDAF7890dd378_0x5c2164e9e03acb4062b6590ee8bf56b0e91de60d2fea0d68b1c0e1aeb5adf43e&safe=eth:0xf2964cCcB7CDA9e808aaBe8DB0DDDAF7890dd378, https://app.safe.global/transactions/tx?id=multisig_0xDb56Fb8F49997Aa1eaa91ebA578fb5992FE22ceF_0x56eed2fa6af6d3c63641842875d20bac661be7a9aecc82c6b0f7025f425e0ab9&safe=oeth:0xDb56Fb8F49997Aa1eaa91ebA578fb5992FE22ceF, https://app.safe.global/transactions/tx?id=multisig_0xC1167F7209A7434252e427Ad96693ccf6FB2755F_0xd582f332761cbaef72189ba85458b48500e9499a5ea8333749f2f376d2ab5f32&safe=arb1:0xC1167F7209A7434252e427Ad96693ccf6FB2755F, https://app.safe.global/transactions/tx?id=multisig_0x95e687bA2d2A791B0246d66bC4fbdD0457dCab19_0xec96999289a9d9b2ad5185f2d215b230af261a8e69141edad751d29032ab2fbd&safe=matic:0x95e687bA2d2A791B0246d66bC4fbdD0457dCab19, https://app.safe.global/transactions/tx?id=multisig_0xFE431e08C415FA4A4e3778da19bff3c1659154B5_0x9ce0fc556bfe257767dc13b30201a442c8ade0eae0987ecd10b2fa8935b9b19e&safe=gno:0xFE431e08C415FA4A4e3778da19bff3c1659154B5, https://app.safe.global/transactions/tx?id=multisig_0x06D63fb4f3F9B8235E71ff4AE82958a45B3dd4A8_0x4da4a94f57df202e387825379d58fd14cb4cde4da5a31cb4493709a6902e9013&safe=bnb:0x06D63fb4f3F9B8235E71ff4AE82958a45B3dd4A8
- [x] PR to Bridge UI: https://github.com/CoinHippo-Labs/connext-bridge/pull/241
- [x] PR to Connextscan: https://github.com/CoinHippo-Labs/connextscan-ui/pull/136
- [x] Lockbox Adapter deployed: https://bscscan.com/tx/0x952b26225c8d60aab617a493b879e5444f2c45c02134458d40d700102fc329a4
- [x] Slow path tested: https://connextscan.io/tx/0xf376790e39e8526a776868fc8e1c53793c5b602c289604a00e7553fc7d711dac
- [x] Router liquidity added and fast path tested: https://connextscan.io/tx/0x03c80a8a069ba75b265ec6ed524ed7da5178006125033386202a349dec6107ca
