### ISSUE TITLE
DappRadar Polygon xERC20 Whitelisting

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#5265]
## Token Details

This is a new deployment of the RADAR xERC20 on Polygon. 

- Name: DappRadar
- Symbol: RADAR
- Chains: Polygon

## Tasks

- [x] PR to chaindata: N/A
- [x] PR to monorepo allowlist config: https://github.com/connext/monorepo/pull/5264
- [x] Whitelisting complete: https://app.safe.global/transactions/tx?id=multisig_0x95e687bA2d2A791B0246d66bC4fbdD0457dCab19_0x60f5418ab2d849429877924f86e1e667b7a1c2e04231a74091537e744dc0e104&safe=matic:0x95e687bA2d2A791B0246d66bC4fbdD0457dCab19
- [x] PR to Bridge UI: https://github.com/CoinHippo-Labs/connext-bridge/pull/255
- [x] PR to Connextscan: https://github.com/CoinHippo-Labs/connextscan-ui/pull/133
- [x] Lockbox Adapter deployed: N/A
- [x] Slow path tested: https://connextscan.io/tx/0x2790a17483094d9c98abc66bdf89293ab854db89b2a428b7ceed414b0d2a36e4
- [x] Router liquidity added and fast path tested: https://connextscan.io/tx/0xfaaee8dff5c3bb82eb0f8b1b2be5788abed6cdc4eaedec0995747429a0c696be, https://connextscan.io/tx/0x9feb9db3e3bf6c0276361dd08901fb00fde58a0ab40ed085ebeeaa40d011a943

**Comment by just-a-node** [comment]
Ready to merge UI PRs on DappRadar's green light (Monday, December 11th).
