### ISSUE TITLE
Deploy Bridge Adapters and Registries to all chains

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#5266]
## Background

Need to deploy BridgeAdapter and Registry to all other chains and register all the current assets to the registry.

## Tasks

- [x] Deploy adapters to all chains
- [x] Deploy registry to all chains
- [x] Register all current assets to all registries

**Comment by just-a-node** [comment]
Registries:
```
mainnet = https://etherscan.io/address/0xFa6c35C88e03338b13cffC9a5A143a2951B7f2fF
polygon = https://polygonscan.com/address/0x3606b0d9c84224892c7407d4e8dcfd7e9e2126a2
optimism = https://optimistic.etherscan.io/address/0x5543eafd20e25fbbbd66e2c154ff8ff8407e3a57
arb = https://arbiscan.io/address/0x63828ede703f981a3c4a4460b730faeb97028df1
gnosis = https://gnosisscan.io/address/0x2056c11b071ae4cdd55007136c2493f3d4c1b678
bnb = https://bscscan.com/address/0x222af8c1411dc8b125338cf876547b03467bb3d1
linea = https://lineascan.build/address/0x11984dc4465481512eb5b777e44061c158cf2259
```

**Comment by just-a-node** [comment]
Adapters:

ethereum: https://etherscan.io/address/0x28496853Bc91144eefd5771144C4f6C6Af813167
polygon: https://polygonscan.com/address/0x6777c6713F13e499232B3a0CdA246e357a9Cf5EB
optimism: https://optimistic.etherscan.io/address/0x81dADc774d2ae44Eb30D2290d076Ae67F9800bd5
arb: https://arbiscan.io/address/0x0B52cA1406eeA3Ce1fcc37dC0121845eF1de3Ae8
gnosis: https://gnosisscan.io/address/0x3Cb55bFBB1f4973FCb9705Bab4aBb7E72BF85eAF
bnb: https://bscscan.com/address/0xB71D06f2e73918386B75c24dD26c95DD938f7912

**Comment by just-a-node** [comment]
All assets with `is_erc20: true` registered in registries.

**Comment by just-a-node** [comment]
Testnet Registries:
```
goerli = https://goerli.etherscan.io/address/0x8d8B8eF5Fa6aF115EC84B2f38d4705B7CC8a9AA1
```

Testnet Adapters:
```
goerli = https://goerli.etherscan.io/address/0x82adad4d1e91e0c569a16c4ce1da0046173ee0a7
```

**Comment by prathmeshkhandelwal1** [comment]
Registers:
```
Sepolia: https://sepolia.etherscan.io/address/0x2a3fe9a49fb50536f1ed099192c2ae2404de7bb5#code
Op-sepolia https://sepolia-optimism.etherscan.io/address/0x18b5b08b10a2e351180f07e31f4fef94d14e28f6
Arb-Sepolia: https://sepolia.arbiscan.io/address/0x343d827d5109e8038bbb71e9ba4f3fd0d546b9ff
```

LockboxAdapters
```
Adapter Sepolia:https://sepolia.etherscan.io/address/0xcF021fCFB9bd72E5aA7ab390cFA4fCfDF895c7Cf#code
OP-Sepolia: https://sepolia-optimism.etherscan.io/address/0x20b4789065DE09c71848b9A4FcAABB2c10006FA2#code
arb sepolia: https://sepolia.arbiscan.io/address/0x0f4Fe4903d01E0deb067A7297453fBEFdC36D189#code
```
