### ISSUE TITLE
xoLIT Mainnet xERC20 Whitelisting

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#5318]
## Token Details

- Name: xoLIT
- Symbol: xoLIT
- Chains: Ethereum, Arbitrum

## Tasks

- [x] PR to chaindata: https://github.com/connext/chaindata/pull/111
- [x] PR to monorepo allowlist config: https://github.com/connext/monorepo/pull/5330
- [x] Whitelisting complete: https://app.safe.global/transactions/tx?id=multisig_0xC1167F7209A7434252e427Ad96693ccf6FB2755F_0x01554ba0adc681d9b1490811f57116eeb285828b7fb1ca8695e6736720b53a90&safe=arb1:0xC1167F7209A7434252e427Ad96693ccf6FB2755F, https://app.safe.global/transactions/tx?id=multisig_0xf2964cCcB7CDA9e808aaBe8DB0DDDAF7890dd378_0x35459d8b2260ff1042365e1407893b50b5c896487f22c73fe507ee0d6a3d8654&safe=eth:0xf2964cCcB7CDA9e808aaBe8DB0DDDAF7890dd378
- [x] PR to Bridge UI: https://github.com/CoinHippo-Labs/connext-bridge/pull/277/
- [x] PR to Connextscan: https://github.com/CoinHippo-Labs/connextscan-ui/pull/143
- [x] Lockbox Adapter deployed: https://etherscan.io/tx/0x536f8eeaccdd75580afc4d0fa5d65d118e52cf5ab527c9a66dbded8e4d5fc50e, https://arbiscan.io/tx/0xfd9d3e091a7254dae871f9965196b2d777d09bfa9be0f24cd739f0e1efb5161b
- [x] Slow path tested: https://connextscan.io/tx/0x34cf98901d2f75400ad268c1b6cc70c59f0ec7fc64ffb585d7e8fbd65bc947f2
- [x] Router liquidity added and fast path tested: https://connextscan.io/tx/0xcbabeaeb513ec3e8ac13e41d9258d0650422af766552a7ccb50edae437f06354
