### ISSUE TITLE
[QUID] [Mainnet] xERC20 Whitelisting

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [connext/monorepo#5336]
## Token Details

- Name: QUID
- Symbol: QUID
- Chains: Ethereum, Optimism, Arbitrum, Polygon, Gnosis, BSC, Mode

## Tasks

- [x] PR to chaindata: _\<link to PR\>_
- [x] PR to monorepo allowlist config: _\<link to PR\>_
- [x] Whitelisting complete: _\<link to transaction(s)\>_
- [x] PR to Bridge UI: https://github.com/connext/frontend/pull/10
- [x] PR to Connextscan: https://github.com/connext/frontend/pull/10
- [x] Registeries: https://etherscan.io/tx/0x4d743e41c766c203a02aaa05afc200a495f3b868f76c8b7f7e1ae3702c047910 
- [x] Slow path tested: pending
- [x] Router liquidity added and fast path tested: NA

**Comment by just-a-node** [comment]
@prathmeshkhandelwal1 Please update this task

**Comment by preethamr** [comment]
@prathmeshkhandelwal1 Could you double check this, and close ?

**Comment by prathmeshkhandelwal1** [comment]
Yes, I will be adding all the related links for above template, but this is done

**Comment by just-a-node** [comment]
@prathmeshkhandelwal1 Link the required info (PRs, etc) and close out.
