### ISSUE TITLE
Multiple (two) LH lambda instances run simultaneously

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#5413]
## Background

We have notice LH propose that expected to only run one instance for every cron frequency are sometimes found to run two 
<img width="1400" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFI3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ece0c68b1e2df06bd9035c6e54c0909b6909d298/image.png" alt="image.png" />

### Linked Issues & Documentation
https://github.com/connext/monorepo/pull/5129/files

However `propogate` seems to be working fine (every 5 mins)
<img width="1273" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFo3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d7dbc11d18adfb018ae13be2cd3908b0386173c6/image.png" alt="image.png" />

## Definition Of Done

- [ ] Check if the [fix for LH SendOutBoundRoot i](https://github.com/connext/monorepo/pull/5129)s also needed for other LH lambdas in the system.
- [ ] Update and test the fix, if needed
- [ ] Deploy to prod
