### ISSUE TITLE
xNST Testnet xERC20 Whitelisting

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#5450]
## Token Details

- Name: xNST
- Symbol: xNST
- Chains: Goerli, Mumbai

## Tasks

- [x] PR to chaindata: https://github.com/connext/chaindata/pull/115
- [x] PR to monorepo allowlist config: https://github.com/connext/monorepo/pull/5542
- [x] Whitelisting complete: https://goerli.etherscan.io/tx/0xca6918ba0fc5a58b8a32d6a0fc8e10b1bcceb79930851cf294f6a7c729d08218, https://mumbai.polygonscan.com/tx/0xc35e2e93bee0c3c5d4906ae0def72d83bb8e54179c36b3a91a06e3bdb64a28ac
- [x] PR to Bridge UI: https://github.com/CoinHippo-Labs/connext-bridge/pull/292
- [x] PR to Connextscan: https://github.com/CoinHippo-Labs/connextscan-ui/pull/149
- [x] xERC20s added to Connext registries: https://goerli.etherscan.io/tx/0x794c154db41bd9e689478aca35b4e25a3715b418db5e548a691447f3aa3771b1
- [N/A] Tracking sheet updated with xERC20 mapping: https://docs.google.com/spreadsheets/d/1_UL3OCR1Ms8dmqYpAIibihb90a8AtBfb6G9PuqKQStY
- [x] Slow path tested: https://testnet.connextscan.io/tx/0xccca5b99b64d5b252e1d7aafcb316ec8d5a7947e5553447cd94de7de01c04c4d
- [x] Router liquidity added and fast path tested: https://testnet.connextscan.io/tx/0x0ededba32cb7bf583f6c36fb217f476abffc980357a3d392b20ce0138f177697, https://testnet.connextscan.io/tx/0xb5a0263d0179bcde1c5e04b97415bfca21110a0ec6f0ef5adf76baf434388351
