### ISSUE TITLE
[EstateX] [Testnet] xERC20 Whitelisting

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [connext/monorepo#5514]
## Token Details

- Name: EstateX
- Symbol: ESX
- Chains: Goerli, Mumbai

## Tasks

- [x] PR to chaindata: _\<link to PR\>_
- [x] PR to monorepo allowlist config: _\<link to PR\>_
- [x] Whitelisting complete: _\<link to transaction(s)\>_
- [x] PR to Bridge UI: _\<link to PR\>_
- [x] PR to Connextscan: _\<link to PR\>_
- [x] xERC20s added to Connext registries: _\<link to transaction(s)\>_
- [ ] Tracking sheet updated with xERC20 mapping: https://docs.google.com/spreadsheets/d/1_UL3OCR1Ms8dmqYpAIibihb90a8AtBfb6G9PuqKQStY
- [ ] Slow path tested: _<link to transfer(s)>_
- [x] Router liquidity added and fast path tested: _\<link to transfer(s)\>_

**Comment by prathmeshkhandelwal1** [comment]
Added in UIs

**Comment by prathmeshkhandelwal1** [comment]
Tested, they agreed to move to mainnet
