### ISSUE TITLE
[sdk-core] Add Gelato Service

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [connext/monorepo#5549]
## Background

Add all the gelato API method that are needed for functions to get the `estimateRelayerFess` and `calculateAmountRecieved`

### Proposed Solution

Create a new class gelatoService which can have all the inherit functions for the gelato APIs
Including methods: 
- `getConversionRate`
- `getGelatoOracles`
- `isOracleActive`
- `getGelatoEstimatedFee`

## Definition Of Done

Implementation of all the functions listed above with a static way of initing the class.

## Tasks

- [] `getConversionRate`
- [] `getGelatoOracles`
- [] `isOracleActive`
- [] `getGelatoEstimatedFee`
- [] Tests for all the above functions

### Acceptance Criteria

- [] Able to consume class in the main functions in connext class
- [] All test cases passing
