### ISSUE TITLE
GovernLabs Testnet xERC20 Whitelisting

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#5605]
## Token Details

- Name: GovernTest
- Symbol: xGovT
- Chains: Goerli, Mumbai, Linea

## Tasks

- [ ] PR to chaindata: _\<link to PR\>_ 
- [x] PR to monorepo allowlist config: https://github.com/connext/monorepo/pull/5585
- [x] Whitelisting complete: https://goerli.etherscan.io/tx/0x78ff5e5d2c6de0ba14685e77feadaf80defe30960cddeccc3f57b80b8927beae, https://mumbai.polygonscan.com/tx/0xe924512c98f529aae46c90f39bf1fb6b8fbdb991867c0ac469a0c013c0195571, https://explorer.goerli.linea.build/tx/0xbb8006bb610b6b4ec3c3f8fdb8372888c641418184e04245be9eb1e8c1e4485a
- [ ] PR to Bridge UI: _\<link to PR\>_
- [ ] PR to Connextscan: _\<link to PR\>_
- [x] xERC20s added to Connext registries: N/A
- [ ] Tracking sheet updated with xERC20 mapping: https://docs.google.com/spreadsheets/d/1_UL3OCR1Ms8dmqYpAIibihb90a8AtBfb6G9PuqKQStY
- [ ] Slow path tested: _<link to transfer(s)>_
- [ ] Router liquidity added and fast path tested: _\<link to transfer(s)\>_
