### ISSUE TITLE
Prepare Base launch

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#5650]
## Background

Assets to support:
- USDC
- ETH

## Tasks

- [x] Whitelist and deploy assets
- [x] Initialize pools
- [x] Bootstrap test liquidity for pools/routers
- [x] Set up configs for UI, prepare PRs
- [x] Run through [testing checklist](https://www.notion.so/connext/Base-Launch-e2ba1a14f8404dcd855c8259b0d57375)
