### ISSUE TITLE
[config] Update Gelato addresses

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#5654]
## Background

Need to add new Gelato relayer addresses:

- Non-zk-sync: 
- Zk-sync:

### Linked Issues & Documentation

- List of linked issues, external links, etc

## Definition Of Done

New Gelato contracts are whitelisted relayers

## Tasks

- [ ] Gelato relayers added to config
- [ ] Protocol admins whitelisted; added by owner
- [ ] Blacklist enabled
- [ ] Chain-specificity enabled
