### ISSUE TITLE
[inrETH] [Testnet] xERC20 Whitelisting

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [connext/monorepo#5728]
## Token Details

- Name: InrETH
- Symbol:InrETH
- Chains: Goerli, Mumbai

## Tasks

- [x] PR to chaindata: https://github.com/connext/chaindata/pull/128
- [x] PR to monorepo allowlist config: https://github.com/connext/monorepo/pull/5707
- [x] Whitelisting complete: _\<link to transaction(s)\>_
- [x] PR to Bridge UI: https://github.com/CoinHippo-Labs/connext-bridge/pull/317
- [x] PR to Connextscan: https://github.com/CoinHippo-Labs/connextscan-ui/pull/162
- [x] xERC20s added to Connext registries:
- https://goerli.etherscan.io/tx/0x7c498e1284baa73663407d7bd64339c873b605956d1650de963475665866ce8e
- https://mumbai.polygonscan.com/tx/0xa00227d118e7660d38db0d2e91aa76236318bfc0700e3a2c66bd116c163b990c
- [ ] Tracking sheet updated with xERC20 mapping: https://docs.google.com/spreadsheets/d/1_UL3OCR1Ms8dmqYpAIibihb90a8AtBfb6G9PuqKQStY
- [ ] Slow path tested: _<link to transfer(s)>_ _Cannot test due to goerli_
- [x] Router liquidity added and fast path tested: _\<link to transfer(s)\>_

**Comment by prathmeshkhandelwal1** [comment]
Closing this out as completed, slow path tx not tested due to slow path broken
