### ISSUE TITLE
xezETH Testnet xERC20 Whitelisting

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#5744]
## Token Details

- Name: xezETH
- Symbol: xezETH
- Chains: Goerli, Op-goerli

## Tasks

- [ ] PR to chaindata: _\<link to PR\>_
- [ ] PR to monorepo allowlist config: _\<link to PR\>_
- [ ] Whitelisting complete: _\<link to transaction(s)\>_
- [ ] PR to Bridge UI: _\<link to PR\>_
- [ ] PR to Connextscan: _\<link to PR\>_
- [ ] xERC20s added to Connext registries: _\<link to transaction(s)\>_
- [ ] Tracking sheet updated with xERC20 mapping: https://docs.google.com/spreadsheets/d/1_UL3OCR1Ms8dmqYpAIibihb90a8AtBfb6G9PuqKQStY
- [ ] Slow path tested: _<link to transfer(s)>_
- [ ] Router liquidity added and fast path tested: _\<link to transfer(s)\>_
