### ISSUE TITLE
[TOKEN] [Mainnet/Testnet] xERC20 Whitelisting

### ISSUE THREAD

**Issue by JimmyDal** [connext/monorepo#5761]
## Token Details

- Name: TOKEN
- Symbol: TKN
- Chains: Ethereum, Optimism, Arbitrum, Polygon, Gnosis, BSC

## Tasks

- [ ] PR to chaindata: _\<link to PR\>_
- [ ] PR to monorepo allowlist config: _\<link to PR\>_
- [ ] Whitelisting complete: _\<link to transaction(s)\>_
- [ ] PR to Bridge UI: _\<link to PR\>_
- [ ] PR to Connextscan: _\<link to PR\>_
- [ ] xERC20s added to Connext registries: _\<link to transaction(s)\>_
- [ ] Tracking sheet updated with xERC20 mapping: https://docs.google.com/spreadsheets/d/1_UL3OCR1Ms8dmqYpAIibihb90a8AtBfb6G9PuqKQStY
- [ ] Slow path tested: _<link to transfer(s)>_
- [ ] Router liquidity added and fast path tested: _\<link to transfer(s)\>_

**Comment by preethamr** [comment]
@JimmyDal Is there an xERC20 to be whitelisted
