### ISSUE TITLE
[InstETH] [Mainnet] xERC20 Whitelisting

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [connext/monorepo#5784]
## Token Details

- Name: InstETH
- Symbol: InstETH
- Chains: Ethereum, Arbitrum 

## Tasks

- [x] PR to chaindata: https://github.com/connext/chaindata/pull/133#pullrequestreview-1912394073
- [x] PR to monorepo allowlist config: https://github.com/connext/monorepo/pull/5782
- [x] Whitelisting complete: https://app.safe.global/transactions/tx?id=multisig_0xC1167F7209A7434252e427Ad96693ccf6FB2755F_0x9b1f73599959fb8c854674cbf859bfba796fa531e53a95b6cfad227e4ec3a48f&safe=arb1:0xC1167F7209A7434252e427Ad96693ccf6FB2755F, https://app.safe.global/transactions/tx?id=multisig_0xf2964cCcB7CDA9e808aaBe8DB0DDDAF7890dd378_0x8a6e696c1a6a530760eea13089133cae0f7b9f707695edc0f0ea2b3d7d4cdd44&safe=eth:0xf2964cCcB7CDA9e808aaBe8DB0DDDAF7890dd378
- [x] PR to Bridge UI: https://github.com/CoinHippo-Labs/connext-bridge/pull/324
- [x] PR to Connextscan: https://github.com/CoinHippo-Labs/connextscan-ui/pull/168
- [x] xERC20s added to Connext registries: 
ETH: https://etherscan.io/tx/0xda20aa1e90b79644d3711de9e216c8937bb6639c5f2b1b2aa065188686ed0cba
Arbi: https://arbiscan.io/tx/0xce878147e50767bf738b7aa58f2188ed36cbe64d06e5460aeeb732f7fca35379
- [x] Tracking sheet updated with xERC20 mapping: https://docs.google.com/spreadsheets/d/1_UL3OCR1Ms8dmqYpAIibihb90a8AtBfb6G9PuqKQStY
- [x] Slow path tested: https://connextscan.io/tx/0xc7e4bdde565639adfb46c7e9c79035d821ff8f133c0ebd37c1eb2d73b471e51c
- [x] Router liquidity added and fast path tested: http://localhost:3000/tx/0x01cb622984f66e1a305e695fe4fd8c5e0aa73e36013c28e810f3cb4e3e34dbc0
