### ISSUE TITLE
[ezETH] [Mainnet] xERC20 Whitelisting

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [connext/monorepo#5793]
## Token Details

- Name: ezETH
- Symbol: ezETH
- Chains: Ethereum, Arbitrum

## Tasks

- [x] PR to chaindata: https://github.com/connext/chaindata/pull/135
- [x] PR to monorepo allowlist config: https://github.com/connext/monorepo/pull/5794
- [x] Whitelisting complete: https://app.safe.global/transactions/tx?id=multisig_0xC1167F7209A7434252e427Ad96693ccf6FB2755F_0x9b1f73599959fb8c854674cbf859bfba796fa531e53a95b6cfad227e4ec3a48f&safe=arb1:0xC1167F7209A7434252e427Ad96693ccf6FB2755F, https://app.safe.global/transactions/tx?id=multisig_0xf2964cCcB7CDA9e808aaBe8DB0DDDAF7890dd378_0x8a6e696c1a6a530760eea13089133cae0f7b9f707695edc0f0ea2b3d7d4cdd44&safe=eth:0xf2964cCcB7CDA9e808aaBe8DB0DDDAF7890dd378
- [x] PR to Bridge UI: https://github.com/CoinHippo-Labs/connext-bridge/pull/326
- [x] PR to Connextscan: https://github.com/CoinHippo-Labs/connextscan-ui/pull/170
- [x] xERC20s added to Connext registries: https://etherscan.io/tx/0x4a546a1a371f4dd9cf28c699f8b1509c638b69b05b5e650241fa5a43b9a5c935, https://arbiscan.io/tx/0xb242c77d81f8df6ae274d92689ef77d1479d99c6a482af0e5f7b1d386540a5a8
- [ ] Tracking sheet updated with xERC20 mapping: https://docs.google.com/spreadsheets/d/1_UL3OCR1Ms8dmqYpAIibihb90a8AtBfb6G9PuqKQStY
- [x] Slow path tested: https://connextscan.io/tx/0x8745b33779d5be6ff50da2a3101b6f2e2695dc3ab3d7c8703fe7cf2daa1fdbde
- [x] Router liquidity added and fast path tested: https://connextscan.io/tx/0xa3180b8459c8f6b6fbe74522d76c9aeba76e802303747eb2137807a34fb01aa0

**Comment by just-a-node** [comment]
Added bridge PRs, router liq, slow/path tranfers.
