### ISSUE TITLE
Make SDK updates to support Sepolia testnet

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#5839]
## Background

Sepolia testnet has been deployed. Currently lives in staging testnet environment. Depending on when this task is handled, ensure the SDK is aware of the right contracts for the right testnet environments.

## Definition Of Done

SDK uses Sepolia testnet environment.

## Tasks

- [x] Make changes to SDK config to handle new Sepolia testnet env
- [x] Release with new Sepolia testnet Connext contracts
- [x] Release with new Sepolia testnet peripheral contracts (registries + adapters), then update https://github.com/connext/monorepo/issues/5266
- [x] Launch updates on testnet UI

**Comment by prathmeshkhandelwal1** [comment]
For sepolia: 
bridge UI: https://connext-bridge-testnet-staging-cbb55supq-coinhippo.vercel.app/
Connextscan UI: https://connextscan-testnet-staging-git-feat-staging-sepolia-coinhippo.vercel.app/
SDK version to support sepolia: 2.3.0-alpha.10 (Note that any georli testnet domains will break the sdk, this should be only used for sepolia)
