### ISSUE TITLE
Cutover from old to new UI repos

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#5840]
## Background

Deploy the new frontend repos and configure our current domains to point to the new deployments.

## Definition Of Done

We need to check feature parity between the deployments since the new repos have been migrated to Typescript. 

## Tasks

- [x] QA feature parity: https://www.notion.so/connext/Connext-UIs-Feature-Parity-QA-52bbb3ce18e042d78e029e1d565c4fc7?pvs=4
- [x] CI to vercel (`feat/` branches create staging links, `main` deploys different environments automatically)
- [x] Replay all new commits from old repo to new repo
- [x] Configure domains in new deployments

**Comment by just-a-node** [comment]
QA doc ready. Enlisting Kate's help with running through test cases in preparation for the cutover.

**Comment by prathmeshkhandelwal1** [comment]
## Changes to new UI

- Latest env along with messages
- Blast changes
- https://github.com/CoinHippo-Labs/connext-bridge/commit/22f473b5218a76dd8414038336a357964b0030e8 (WETH as default asset)
- New time estimates
- Remove tokens grouping
- https://github.com/CoinHippo-Labs/connext-bridge/commit/a7654dce3e1aff8b2099120e206ada8d73a88e8d (New messaging)
- Latest SDK version migration
- New twitter link https://github.com/CoinHippo-Labs/connext-bridge/commit/82dbf0aadf87262e45ff70947928c2c3a4643c92
- Unhide scroll bar https://github.com/CoinHippo-Labs/connext-bridge/commit/21a598216e6e2f9b5d140be34dedb0c59c7a39bb
- Latest RPCs
- Adding faucets: https://github.com/CoinHippo-Labs/connext-bridge/commit/74dbc6487029b834931b62a2959aaef4afc14b74
- Add lower staticPaths https://github.com/CoinHippo-Labs/connext-bridge/commit/949b8ad301bae5b589adb2e26eb340581de5b00e

**Comment by prathmeshkhandelwal1** [comment]
https://github.com/connext/frontend/pull/7
