### ISSUE TITLE
[GOAT] [Mainnet] xERC20 Whitelisting

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#5845]
## Token Details

- Name: Goat Trading
- Symbol: GOAT
- Chains: Ethereum, Base, Arbitrum, BSC

## Tasks

- [ ] PR to chaindata: _https://github.com/connext/chaindata/pull/132
- [ ] PR to monorepo allowlist config: https://github.com/connext/monorepo/pull/5770
- [ ] Whitelisting complete: _\<link to transaction(s)\>_
- [ ] PR to Bridge UI: _\<link to PR\>_
- [ ] PR to Connextscan: _\<link to PR\>_
- [ ] xERC20s added to Connext registries: _\<link to transaction(s)\>_
- [ ] Tracking sheet updated with xERC20 mapping: https://docs.google.com/spreadsheets/d/1_UL3OCR1Ms8dmqYpAIibihb90a8AtBfb6G9PuqKQStY
- [ ] Slow path tested: _<link to transfer(s)>_
- [ ] Router liquidity added and fast path tested: _\<link to transfer(s)\>_

**Comment by prathmeshkhandelwal1** [comment]
Moving it in backlog, Not working on it rn
