### ISSUE TITLE
Sepolia testnet pool for liquidity simulations

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#5846]
## Background

We need a pool on Sepolia that we can use to test liquidity hypotheses. Ideally on testnet with a mintable token (TestToken or another version of it). 

## Definition Of Done

A new token with a new pool exists on Sepolia.

## Tasks

- [ ] Deploy new token
- [ ] Set up new pool
- [ ] Give relevant functions to Anton for minting, depositing, withdrawing, and calculating slippage
