### ISSUE TITLE
[ESX] [Mainnet] xERC20 Whitelisting

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [connext/monorepo#5863]
## Token Details

- Name: ESX
- Symbol: ESX
- Chains: BSC, ETH, Polygon

## Tasks

- [ ] PR to chaindata: _\<link to PR\>_
- [ ] PR to monorepo allowlist config: _\<link to PR\>_
- [x] Whitelisting complete: https://app.safe.global/transactions/tx?id=multisig_0x06D63fb4f3F9B8235E71ff4AE82958a45B3dd4A8_0x4aa706a97e6114626e56043b36b5845972c69453c707a79098ddd8fc7e813907&safe=bnb%3A0x06D63fb4f3F9B8235E71ff4AE82958a45B3dd4A8, https://app.safe.global/transactions/tx?id=multisig_0x95e687bA2d2A791B0246d66bC4fbdD0457dCab19_0xcc271c2ee13d5261a3575fe64832a76b3109fcab41dc6e4b3cd71b092b829bbf&safe=matic%3A0x95e687bA2d2A791B0246d66bC4fbdD0457dCab19, https://app.safe.global/transactions/tx?id=multisig_0xf2964cCcB7CDA9e808aaBe8DB0DDDAF7890dd378_0xf37ab90345092f04182b6d98c5793256532d4dba66bdf7d9b4837228fc8c228f&safe=eth%3A0xf2964cCcB7CDA9e808aaBe8DB0DDDAF7890dd378
- [ ] PR to Bridge UI: _\<link to PR\>_
- [ ] PR to Connextscan: _\<link to PR\>_
- [ ] xERC20s added to Connext registries: _\<link to transaction(s)\>_
- [ ] Tracking sheet updated with xERC20 mapping: https://docs.google.com/spreadsheets/d/1_UL3OCR1Ms8dmqYpAIibihb90a8AtBfb6G9PuqKQStY
- [ ] Slow path tested: _<link to transfer(s)>_
- [ ] Router liquidity added and fast path tested: _\<link to transfer(s)\>_

**Comment by prathmeshkhandelwal1** [comment]
Closing this out as they are up on UI
