### ISSUE TITLE
Sunset Goerli Testnet-Prod env

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#5928]
## Background

Support for goerli among providers is dropping rapidly.

## Definition Of Done

Sepolia staging-env is migrated to testnet-prod, and

## Tasks

- [x] Renzo is given one last notice on this
- [x] Fully resolve https://github.com/connext/monorepo/pull/5927 for sepolia deployment
- [x] Deploy to testnet-prod
- [x] Purge testnet db, and sync sepolia state from staging
- [x] Validate testnet UI, update UI domains, and SDK for supported testnet domains
