### ISSUE TITLE
[Swapr] [Testnet] xERC20 Whitelisting

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [connext/monorepo#5934]
## Token Details

- Name: Swapr
- Symbol: Swapr
- Chains: Sepolia, arb-sepolia

## Tasks

- [ ] PR to chaindata: _\<link to PR\>_
- [x] PR to monorepo allowlist config: https://github.com/connext/monorepo/pull/5933
- [x] Whitelisting complete: https://sepolia.etherscan.io/tx/0xc7527fb0381f22fbb9036ede98b5c540317a593893b440a9a44078e25c2495cc
- [x] PR to Bridge UI:https://github.com/CoinHippo-Labs/connext-bridge/pull/373
- [x] PR to Connextscan: https://github.com/CoinHippo-Labs/connextscan-ui/pull/189
- [x] xERC20s added to Connext registries
- [ ] Tracking sheet updated with xERC20 mapping: https://docs.google.com/spreadsheets/d/1_UL3OCR1Ms8dmqYpAIibihb90a8AtBfb6G9PuqKQStY
- [x] Slow path tested: https://connextscan-testnet-staging-git-feat-staging-sepolia-coinhippo.vercel.app/tx/0x1b019b4ee499158e4474e48371763cc59ae3d1bfe1f5a33eb478cb122c065c79
- [ ] Router liquidity added and fast path tested: _\<link to transfer(s)\>_
