### ISSUE TITLE
Fix asset prices retrieved by carto

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#5969]
## Background

Not all asset prices are being populated in carto with the correct prices. We currently use Coingecko's public API. Might be hitting rate limits and/or not handling errors from the API.

## Definition Of Done

All assets saved in the `asset_prices` table are correct.

## Tasks

- [ ] Handle API errors, use last updated price as fallback
- [ ] Save a timestamp of last update for each asset
- [ ] Set up private Coingecko api key if needed
