### ISSUE TITLE
Copy of Prepare Scroll Launch

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#5978]
# Background

Assets to support:
- ETH/WETH

# Tasks
- [ ] Whitelist and deploy assets
- [ ] Initialize pools
- [ ] Bootstrap test liquidity for pools/routers
- [ ] Set up configs for UI, prepare PRs
- [ ] Run through [testing checklist](https://www.notion.so/connext/Scroll-Launch-29ee4267d82644a2bafe25c45dab1968)
