### ISSUE TITLE
Hardcapped relayer fee estimates

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#5986]
## Background

Relayer fee estimates should be hard capped by a value pulled from chaindata. These values are determined from recent historical fees paid on each destination chain.

## Tasks

- [x] Fees added to chaindata
- [x] `estimateRelayerFee` in SDK pulls from chaindata
- [x] SDK released and UI updated
