### ISSUE TITLE
[Alchemix USD and ETH] [Mainnet] Whitelisting

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [connext/monorepo#5992]
## Token Details

- Name: Alchemix USD and Alchemix ETH
- Symbol: alUSD , alETH
- Chains: Ethereum, OP, Arbitrum, 

## Tasks

- [x] PR to chaindata: https://github.com/connext/chaindata/pull/148
- [x] PR to monorepo allowlist config: https://github.com/connext/monorepo/pull/5957
- [x] Whitelisting complete: https://app.safe.global/transactions/tx?id=multisig_0xC1167F7209A7434252e427Ad96693ccf6FB2755F_0xa775924dd626964aafe2edd791083e0b5d51ad743a662453056afbbc25b179fd&safe=arb1:0xC1167F7209A7434252e427Ad96693ccf6FB2755F
- [ ] PR to Bridge UI: _\<link to PR\>_
- [ ] PR to Connextscan: _\<link to PR\>_
- [ ] xERC20s added to Connext registries: _\<link to transaction(s)\>_
- [ ] Tracking sheet updated with xERC20 mapping: https://docs.google.com/spreadsheets/d/1_UL3OCR1Ms8dmqYpAIibihb90a8AtBfb6G9PuqKQStY
- [ ] Slow path tested: _<link to transfer(s)>_
- [ ] Router liquidity added and fast path tested: _\<link to transfer(s)\>_

**Comment by prathmeshkhandelwal1** [comment]
Whitelisting completed, Waiting on confirmation of lockboxes on alchemix team, As soon as they update will move forwards with UI PRs

**Comment by prathmeshkhandelwal1** [comment]
https://github.com/connext/monorepo/issues/5993

**Comment by prathmeshkhandelwal1** [comment]
UI PRs enabled, Need to them to flush out balance on connext contarcts to deregister prev assets

**Comment by ekbainova** [comment]
@just-a-node @prathmeshkhandelwal1 #6049 also fixed?
