### ISSUE TITLE
[alUSD/alETH] Mainnet xERC20 Metis Whitelisting

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#6104]
## Token Details
- Name: alUSD, alETH
- Symbol: alUSD, alETH
- Chains: Metis

## Tasks
- [ ] PR to chaindata: https://github.com/connext/chaindata/pull/161
- [ ] PR to monorepo allowlist config: https://github.com/connext/monorepo/pull/6084
- [x] Whitelisting complete: https://andromeda-explorer.metis.io/tx/0x15f9e2be29d870b9b84ed2f52b0fc0fc7e80eb96f6a45589121659a8b9f00b4c, https://andromeda-explorer.metis.io/tx/0x4afbee49b1e157ecec1cd166d65cb6620afb56f7256ccccd80045594559301f0
- [ ] PR to Bridge UI: _\<link to PR\>_
- [ ] PR to Connextscan: _\<link to PR\>_
- [ ] xERC20s added to Connext registries: _\<link to transaction(s)\>_
- [ ] Tracking sheet updated with xERC20 mapping: https://docs.google.com/spreadsheets/d/1_UL3OCR1Ms8dmqYpAIibihb90a8AtBfb6G9PuqKQStY
- [ ] Slow path tested: _<link to transfer(s)>_
- [ ] Router liquidity added and fast path tested: _\<link to transfer(s)\>_

**Comment by just-a-node** [comment]
@prathmeshkhandelwal1 Last steps on this?

**Comment by just-a-node** [comment]
Pending UI config
