### ISSUE TITLE
[API] OAS specification for chimera API

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [connext/monorepo#6145]
## Background

Need to write OAS specifications for chimera API to meet global standard

### Linked Issues & Documentation

- List of linked issues, external links, etc

## Definition Of Done

Describes in 1-2 sentences what the output of the Task is, so that it can be verified by another team member easily. “Feature X is implemented as described and can be verified by using it”

## Tasks

- [ ] Make sure specs are correct
- [ ] Write proper Error cases with codes
- [ ] Create `yaml` specification for OAS
