### ISSUE TITLE
[API] Create Transfers Pagination using PostgresT query

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [connext/monorepo#6232]
## Background

Use PostgresT Queries for creating pagination on `transfers` endpoint

## Tasks

- [ ] Write PostgresT queries
- [ ] Add mockData switch for UI
- [ ] Return the transfers along with cursor [Separate controller for transfers]
